AdvectionCascade.f90 File Reference
Functions/Subroutines
program kentcascadeadvection
subroutine convertfromrelativetolerances (aMesh, tracerMassTol, tracerVarTol, tracerID)
subroutine readnamelistfile (rank)
subroutine initlogger (alog, rank)
Function/Subroutine Documentation
subroutine kentcascadeadvection::convertfromrelativetolerances (type(spheremesh), intent(in) aMesh, real(kreal), intent(inout) tracerMassTol, real(kreal), intent(inout) tracerVarTol, integer(kint), intent(in) tracerID)
Definition at line 302 of file AdvectionCascade.f90.
References planemeshmodule::maximumtracermass(), and planemeshmodule::maximumtracervariation().
subroutine kentcascadeadvection::initlogger (type(logger), intent(out) alog, integer(kint), intent(in) rank)
Definition at line 355 of file AdvectionCascade.f90.
program kentcascadeadvection ()
Definition at line 1 of file AdvectionCascade.f90.
References advectionmodule::advectionrk4timestep(), convertfromrelativetolerances(), refineremeshmodule::initialrefinement(), initlogger(), tracersetupmodule::initonegaussianhilltracer(), advectionmodule::kentcascadevelocity(), sphereremeshmodule::lagrangianremeshtoreference(), bvesetupmodule::nullvorticity(), readnamelistfile(), tracersetupmodule::setonegaussianhilltraceronmesh(), spheremeshmodule::totalmass(), tracersetupmodule::tracervariance(), planeoutputmodule::updatefilename(), and vtkoutputmodule::vtkoutput().
subroutine kentcascadeadvection::readnamelistfile (integer(kint), intent(in) rank)
Definition at line 310 of file AdvectionCascade.f90.