AdvectMovingVortices.f90 File Reference
Functions/Subroutines
program movingvorticesadvection
real(kreal) function testcasetracerexact (xyz, t, rho0, gamma)
subroutine convertfromrelativetolerances (aMesh, tracerMassTol, tracerVarTol, tracerID, lagVarTol)
subroutine readnamelistfile (rank)
subroutine initlogger (alog, rank)
Function/Subroutine Documentation
subroutine movingvorticesadvection::convertfromrelativetolerances (type(spheremesh), intent(in) aMesh, real(kreal), intent(inout) tracerMassTol, real(kreal), intent(inout) tracerVarTol, integer(kint), intent(in) tracerID, real(kreal), intent(inout) lagVarTol)
Definition at line 433 of file AdvectMovingVortices.f90.
References planemeshmodule::maximumlagrangianparametervariation(), planemeshmodule::maximumtracermass(), and planemeshmodule::maximumtracervariation().
subroutine movingvorticesadvection::initlogger (type(logger), intent(out) alog, integer(kint), intent(in) rank)
Definition at line 489 of file AdvectMovingVortices.f90.
program movingvorticesadvection ()
Definition at line 1 of file AdvectMovingVortices.f90.
References advectionmodule::advectionrk4timestep(), convertfromrelativetolerances(), refineremeshmodule::initialrefinement(), initlogger(), sphereremeshmodule::lagrangianremeshtoreference(), advectionmodule::movingvorticesvelocity(), bvesetupmodule::nullvorticity(), readnamelistfile(), tracersetupmodule::setmovingvortstraceronmesh(), testcasetracerexact(), spheremeshmodule::totalmass(), tracersetupmodule::tracervariance(), planeoutputmodule::updatefilename(), and vtkoutputmodule::vtkoutput().
subroutine movingvorticesadvection::readnamelistfile (integer(kint), intent(in) rank)
Definition at line 442 of file AdvectMovingVortices.f90.
real(kreal) function movingvorticesadvection::testcasetracerexact (real(kreal), dimension(3), intent(in) xyz, real(kreal), intent(in) t, real(kreal), intent(in) rho0, real(kreal), intent(in) gamma)
Definition at line 412 of file AdvectMovingVortices.f90.
Referenced by movingvorticesadvection().