AdvectGaussHills.f90 File Reference
Functions/Subroutines
program gaussianhillsadvection
real(kreal) function ghillsexact (xyz, hmax, beta)
subroutine convertfromrelativetolerances (aMesh, tracerMassTol, tracerVarTol, tracerID)
subroutine readnamelistfile (rank)
subroutine initlogger (alog, rank)
Function/Subroutine Documentation
subroutine gaussianhillsadvection::convertfromrelativetolerances (type(spheremesh), intent(in) aMesh, real(kreal), intent(inout) tracerMassTol, real(kreal), intent(inout) tracerVarTol, integer(kint), intent(in) tracerID)
Definition at line 358 of file AdvectGaussHills.f90.
References planemeshmodule::maximumtracermass(), and planemeshmodule::maximumtracervariation().
Referenced by gaussianhillsadvection(), gaussianhillsadvectiondirect(), kentcascadeadvection(), and movingvorticesadvection().
program gaussianhillsadvection ()
Definition at line 1 of file AdvectGaussHills.f90.
References advectionmodule::advectionrk4timestep(), convertfromrelativetolerances(), ghillsexact(), tracersetupmodule::initgaussianhillstracer(), refineremeshmodule::initialrefinement(), initlogger(), sphereremeshmodule::lagrangianremeshtoreference(), advectionmodule::lauritzenetalnondivergentwind(), bvesetupmodule::nullvorticity(), readnamelistfile(), tracersetupmodule::setgaussianhillstraceronmesh(), spheremeshmodule::totalmass(), tracersetupmodule::tracervariance(), planeoutputmodule::updatefilename(), and vtkoutputmodule::vtkoutput().
real(kreal) function gaussianhillsadvection::ghillsexact (real(kreal), dimension(3), intent(in) xyz, real(kreal), intent(in) hmax, real(kreal), intent(in) beta)
Definition at line 344 of file AdvectGaussHills.f90.
Referenced by gaussianhillsadvection(), gaussianhillsadvectiondirect(), and ghillsexact().
subroutine gaussianhillsadvection::initlogger (type(logger), intent(out) alog, integer(kint), intent(in) rank)
Definition at line 411 of file AdvectGaussHills.f90.
Referenced by bvegaussvort(), bvesolidbody(), gaussianhillsadvection(), gaussianhillsadvectiondirect(), kentcascadeadvection(), movingvorticesadvection(), nonlinearsteadyswe(), planerotateadvection(), reversibledipolesmain(), rh4wave(), swedivergenceequationterms(), testcase1(), and twodipolesmain().
subroutine gaussianhillsadvection::readnamelistfile (integer(kint), intent(in) rank)
Definition at line 366 of file AdvectGaussHills.f90.
Referenced by bvegaussvort(), bvesolidbody(), gaussianhillsadvection(), gaussianhillsadvectiondirect(), kentcascadeadvection(), lambtest(), movingvorticesadvection(), planerotateadvection(), planeunittest(), reversibledipolesmain(), rh4wave(), testcase1(), and twodipolesmain().