AdvectGaussHillsDirect.f90 File Reference
Functions/Subroutines
program gaussianhillsadvectiondirect
real(kreal) function ghillsexact (xyz, hmax, beta)
subroutine convertfromrelativetolerances (aMesh, tracerMassTol, tracerVarTol, tracerID)
subroutine readnamelistfile (rank)
subroutine initlogger (alog, rank)
Function/Subroutine Documentation
subroutine gaussianhillsadvectiondirect::convertfromrelativetolerances (type(spheremesh), intent(in) aMesh, real(kreal), intent(inout) tracerMassTol, real(kreal), intent(inout) tracerVarTol, integer(kint), intent(in) tracerID)
Definition at line 333 of file AdvectGaussHillsDirect.f90.
References planemeshmodule::maximumtracermass(), and planemeshmodule::maximumtracervariation().
program gaussianhillsadvectiondirect ()
Definition at line 1 of file AdvectGaussHillsDirect.f90.
References advectionmodule::advectionrk4timestep(), convertfromrelativetolerances(), sphereremeshmodule::directremesh(), ghillsexact(), tracersetupmodule::initgaussianhillstracer(), refineremeshmodule::initialrefinement(), initlogger(), advectionmodule::lauritzenetalnondivergentwind(), bvesetupmodule::nullvorticity(), readnamelistfile(), tracersetupmodule::setgaussianhillstraceronmesh(), spheremeshmodule::totalmass(), tracersetupmodule::tracervariance(), planeoutputmodule::updatefilename(), and vtkoutputmodule::vtkoutput().
real(kreal) function gaussianhillsadvectiondirect::ghillsexact (real(kreal), dimension(3), intent(in) xyz, real(kreal), intent(in) hmax, real(kreal), intent(in) beta)
Definition at line 319 of file AdvectGaussHillsDirect.f90.
References ghillsexact().
subroutine gaussianhillsadvectiondirect::initlogger (type(logger), intent(out) alog, integer(kint), intent(in) rank)
Definition at line 386 of file AdvectGaussHillsDirect.f90.
subroutine gaussianhillsadvectiondirect::readnamelistfile (integer(kint), intent(in) rank)
Definition at line 341 of file AdvectGaussHillsDirect.f90.