BVERH4.f90 File Reference
Functions/Subroutines
program rh4wave
subroutine readnamelistfile (rank)
subroutine converttorelativetolerances (aMesh, maxCircTol, vortVarTol, lagVarTol)
subroutine initlogger (alog, rank)
Function/Subroutine Documentation
subroutine rh4wave::converttorelativetolerances (type(spheremesh), intent(in) aMesh, real(kreal), intent(inout) maxCircTol, real(kreal), intent(inout) vortVarTol, real(kreal), intent(inout) lagVarTol)
Definition at line 457 of file BVERH4.f90.
References spheremeshmodule::averagelagrangianparametervariation(), planemeshmodule::maximumcirculation(), and planemeshmodule::maximumvorticityvariation().
Referenced by lambtest(), planeunittest(), reversibledipolesmain(), rh4wave(), and twodipolesmain().
subroutine rh4wave::initlogger (type(logger), intent(out) alog, integer(kint), intent(in) rank)
Definition at line 465 of file BVERH4.f90.
subroutine rh4wave::readnamelistfile (integer(kint), intent(in) rank)
Definition at line 407 of file BVERH4.f90.
program rh4wave ()
Definition at line 1 of file BVERH4.f90.
References bvedirectsummodule::bverk4timestep(), converttorelativetolerances(), spheremeshmodule::getrossbynumber(), refineremeshmodule::initialrefinement(), initlogger(), bvesetupmodule::initrh4wave(), sphereremeshmodule::lagrangianremeshtoreference(), bvesetupmodule::legendre54(), latlonoutputmodule::lloutputmatlab(), planetracermodule::nulltracer(), readnamelistfile(), bvesetupmodule::rh54vorticity(), tracersetupmodule::setflowmaplatitudetraceronmesh(), bvesetupmodule::setrh4waveonmesh(), spheremeshmodule::totalenstrophy(), planeoutputmodule::updatefilename(), and vtkoutputmodule::vtkoutput().
Referenced by bvesetupmodule::initrh4wave().