BVESolidBodyRotation.f90 File Reference
Functions/Subroutines
program bvesolidbody
subroutine readnamelistfile (rank)
subroutine initlogger (alog, rank)
Function/Subroutine Documentation
program bvesolidbody ()
Definition at line 1 of file BVESolidBodyRotation.f90.
References bvedirectsummodule::bverk4timestep(), tracersetupmodule::initcosinebelltracer(), refineremeshmodule::initialrefinement(), initlogger(), bvesetupmodule::initsolidbodyrotation(), readnamelistfile(), tracersetupmodule::setcosinebelltraceronmesh(), bvesetupmodule::setsolidbodyrotationonmesh(), planeoutputmodule::updatefilename(), and vtkoutputmodule::vtkoutput().
subroutine bvesolidbody::initlogger (type(logger), intent(out) alog, integer(kint), intent(in) rank)
Definition at line 273 of file BVESolidBodyRotation.f90.
subroutine bvesolidbody::readnamelistfile (integer(kint), intent(in) rank)
Definition at line 245 of file BVESolidBodyRotation.f90.