BVESingleGaussianVortex.f90 File Reference
Functions/Subroutines
program bvegaussvort
subroutine readnamelistfile (rank)
subroutine initlogger (alog, rank)
Function/Subroutine Documentation
program bvegaussvort ()
Definition at line 1 of file BVESingleGaussianVortex.f90.
References bvedirectsummodule::bverk4timestep(), spheremeshmodule::getrossbynumber(), tracersetupmodule::initcosinebelltracer(), refineremeshmodule::initialrefinement(), initlogger(), bvesetupmodule::initsinglegaussianvortex(), readnamelistfile(), tracersetupmodule::setcosinebelltraceronmesh(), tracersetupmodule::setflowmaplatitudetraceronmesh(), refineremeshmodule::setrelativeflowmaptol(), refineremeshmodule::setrelativetracertols(), refineremeshmodule::setrelativevorticitytols(), bvesetupmodule::setsinglegaussianvortexonmesh(), spheremeshmodule::totalenstrophy(), spheremeshmodule::totalmass(), planeoutputmodule::updatefilename(), and vtkoutputmodule::vtkoutput().
subroutine bvegaussvort::initlogger (type(logger), intent(out) alog, integer(kint), intent(in) rank)
Definition at line 441 of file BVESingleGaussianVortex.f90.
subroutine bvegaussvort::readnamelistfile (integer(kint), intent(in) rank)
Definition at line 405 of file BVESingleGaussianVortex.f90.