vtkoutputmodule Module Reference
Public Member Functions
subroutine, public updatetitle (self, newtitle)
subroutine, public vtkoutput (self, aMesh)
subroutine, public vtkoutputmidpointrule (self, aMesh)
Detailed Description
Definition at line 1 of file VTKOutput.f90.
Member Function/Subroutine Documentation
subroutine, public vtkoutputmodule::updatetitle (type(vtksource), intent(inout) self, character(len=*), intent(in) newtitle)
Definition at line 148 of file VTKOutput.f90.
Referenced by swedivergenceequationterms().
subroutine, public vtkoutputmodule::vtkoutput (type(vtksource), intent(in) self, type(spheremesh), intent(in) aMesh)
Definition at line 154 of file VTKOutput.f90.
References planemeshmodule::ccwedgesandparticlesaroundpanel(), and panelsmodule::getpanelkind().
Referenced by bvegaussvort(), bvesolidbody(), cubedspheretest(), gaussianhillsadvection(), gaussianhillsadvectiondirect(), icostrianglestest(), kentcascadeadvection(), movingvorticesadvection(), nonlinearsteadyswe(), rh4wave(), swedivergenceequationterms(), and testcase1().
subroutine, public vtkoutputmodule::vtkoutputmidpointrule (type(vtksource), intent(in) self, type(spheremesh), intent(in) aMesh)
Definition at line 363 of file VTKOutput.f90.
The documentation for this module was generated from the following file:
VTKOutput.f90