tracersetupmodule Module Reference
Public Member Functions
subroutine, public initcosinebelltracer (cosBell, lat0, lon0, rr, h0, tracerID)
subroutine, public setcosinebelltraceronmesh (aMesh, cosBell)
subroutine, public setmovingvortstraceronmesh (aMesh, mvt)
subroutine, public initonegaussianhilltracer (gHill, hMax, beta, tracerID)
subroutine, public initgaussianhillstracer (gHills, hmax, beta, tracerID)
subroutine, public setgaussianhillstraceronmesh (aMesh, gHills)
subroutine, public setonegaussianhilltraceronmesh (aMesh, gHill)
subroutine, public setflowmaplatitudetraceronmesh (aMesh, tracerID)
subroutine, public nulltracer (aMesh, nullScalar)
real(kreal) function, public tracervariance (aMesh, tracerID)
Public Attributes
integer(kint), parameter, public cos_bell_nint = 0
integer(kint), parameter, public cos_bell_nreal = 4
integer(kint), parameter, public gauss_hills_n_int = 1
integer(kint), parameter, public gauss_hills_n_real = 2
Detailed Description
Definition at line 1 of file Tracers.f90.
Member Function/Subroutine Documentation
subroutine, public tracersetupmodule::initcosinebelltracer (type(tracersetup), intent(inout) cosBell, real(kreal), intent(in) lat0, real(kreal), intent(in) lon0, real(kreal), intent(in) rr, real(kreal), intent(in) h0, integer(kint), intent(in) tracerID)
Definition at line 120 of file Tracers.f90.
Referenced by bvegaussvort(), bvesolidbody(), and testcase1().
subroutine, public tracersetupmodule::initgaussianhillstracer (type(tracersetup), intent(inout) gHills, real(kreal), intent(in) hmax, real(kreal), intent(in) beta, integer(kint), intent(in) tracerID)
Definition at line 216 of file Tracers.f90.
Referenced by gaussianhillsadvection(), and gaussianhillsadvectiondirect().
subroutine, public tracersetupmodule::initonegaussianhilltracer (type(tracersetup), intent(inout) gHill, real(kreal), intent(in) hMax, real(kreal), intent(in) beta, integer(kint), intent(in) tracerID)
Definition at line 197 of file Tracers.f90.
Referenced by kentcascadeadvection().
subroutine, public tracersetupmodule::nulltracer (type(spheremesh), intent(inout) aMesh, type(tracersetup), intent(in) nullScalar)
Definition at line 325 of file Tracers.f90.
subroutine, public tracersetupmodule::setcosinebelltraceronmesh (type(spheremesh), intent(inout) aMesh, type(tracersetup), intent(in) cosBell)
Definition at line 138 of file Tracers.f90.
Referenced by bvegaussvort(), bvesolidbody(), and testcase1().
subroutine, public tracersetupmodule::setflowmaplatitudetraceronmesh (type(spheremesh), intent(inout) aMesh, integer(kint), intent(in) tracerID)
Definition at line 306 of file Tracers.f90.
Referenced by bvegaussvort(), nonlinearsteadyswe(), and rh4wave().
subroutine, public tracersetupmodule::setgaussianhillstraceronmesh (type(spheremesh), intent(inout) aMesh, type(tracersetup), intent(in) gHills)
Definition at line 235 of file Tracers.f90.
Referenced by gaussianhillsadvection(), and gaussianhillsadvectiondirect().
subroutine, public tracersetupmodule::setmovingvortstraceronmesh (type(spheremesh), intent(inout) aMesh, type(tracersetup), intent(in) mvt)
Definition at line 163 of file Tracers.f90.
Referenced by movingvorticesadvection().
subroutine, public tracersetupmodule::setonegaussianhilltraceronmesh (type(spheremesh), intent(inout) aMesh, type(tracersetup), intent(in) gHill)
Definition at line 262 of file Tracers.f90.
Referenced by kentcascadeadvection().
real(kreal) function, public tracersetupmodule::tracervariance (type(spheremesh), intent(in) aMesh, integer(kint), intent(in) tracerID)
Definition at line 330 of file Tracers.f90.
Referenced by gaussianhillsadvection(), gaussianhillsadvectiondirect(), kentcascadeadvection(), and movingvorticesadvection().
Member Data Documentation
integer(kint), parameter, public tracersetupmodule::cos_bell_nint = 0
Definition at line 52 of file Tracers.f90.
integer(kint), parameter, public tracersetupmodule::cos_bell_nreal = 4
Definition at line 52 of file Tracers.f90.
integer(kint), parameter, public tracersetupmodule::gauss_hills_n_int = 1
Definition at line 52 of file Tracers.f90.
integer(kint), parameter, public tracersetupmodule::gauss_hills_n_real = 2
Definition at line 52 of file Tracers.f90.
The documentation for this module was generated from the following file:
Tracers.f90