spheremeshmodule Module Reference
Public Member Functions
subroutine, public renormalize (self)
subroutine, public resetspherearea (self)
subroutine, public ccwedgesandparticlesaroundpanel (edgeList, vertList, nVerts, self, panelIndex)
real(kreal) function, public totalmass (self, tracerNumber)
real(kreal) function, public totalabsvort (self)
real(kreal) function, public getrossbynumber (self)
real(kreal) function, public totalrelvort (self)
real(kreal) function, public totalenstrophy (self)
integer(kint) function, public locatepoint (self, xyz)
integer(kint) function, public countsubtriangles (self)
real(kreal) function, public maximumcirculation (self)
real(kreal) function, public maximumtracermass (self, tracerID)
real(kreal) function, public maximumtracervariation (self, tracerID)
real(kreal) function, public maximumvorticityvariation (self)
real(kreal) function, public averagelagrangianparametervariation (self)
real(kreal) function, public maximumlagrangianparametervariation (self)
subroutine, public dividepanel (self, panelIndex)
subroutine, public findadjacentpanels (adjPanels, nNeighbors, self, panelIndex)
Detailed Description
Definition at line 1 of file SphereMesh2.f90.
Member Function/Subroutine Documentation
real(kreal) function, public spheremeshmodule::averagelagrangianparametervariation (type(spheremesh), intent(in) self)
Definition at line 524 of file SphereMesh2.f90.
Referenced by converttorelativetolerances().
subroutine, public spheremeshmodule::ccwedgesandparticlesaroundpanel (integer(kint), dimension(:), intent(inout) edgeList, integer(kint), dimension(:), intent(inout) vertList, integer(kint), intent(inout) nVerts, type(spheremesh), intent(in) self, integer(kint), intent(in) panelIndex)
Definition at line 269 of file SphereMesh2.f90.
References panelsmodule::getpanelkind().
integer(kint) function, public spheremeshmodule::countsubtriangles (type(spheremesh), intent(in) self)
Definition at line 439 of file SphereMesh2.f90.
References planemeshmodule::ccwedgesandparticlesaroundpanel().
subroutine, public spheremeshmodule::dividepanel (type(spheremesh), intent(inout) self, integer(kint), intent(in) panelIndex)
Definition at line 947 of file SphereMesh2.f90.
References planemeshmodule::ccwedgesandparticlesaroundpanel(), planemeshmodule::findadjacentpanels(), panelsmodule::getpanelkind(), spheregeommodule::spheremidpoint(), spheregeommodule::spherequadcenter(), and spheregeommodule::spheretricenter().
subroutine, public spheremeshmodule::findadjacentpanels (integer(kint), dimension(:), intent(inout) adjPanels, integer(kint), intent(inout) nNeighbors, type(spheremesh), intent(in) self, integer(kint), intent(in) panelIndex)
Definition at line 1791 of file SphereMesh2.f90.
References planemeshmodule::ccwedgesandparticlesaroundpanel(), panelsmodule::getpanelkind(), and spheregeommodule::spherequadcenter().
real(kreal) function, public spheremeshmodule::getrossbynumber (type(spheremesh), intent(in) self)
Definition at line 383 of file SphereMesh2.f90.
Referenced by bvegaussvort(), and rh4wave().
integer(kint) function, public spheremeshmodule::locatepoint (type(spheremesh), intent(in) self, real(kreal), dimension(3), intent(in) xyz)
Definition at line 424 of file SphereMesh2.f90.
References planemeshmodule::locatepoint().
real(kreal) function, public spheremeshmodule::maximumcirculation (type(spheremesh), intent(in) self)
Definition at line 471 of file SphereMesh2.f90.
References planemeshmodule::maximumcirculation().
real(kreal) function, public spheremeshmodule::maximumlagrangianparametervariation (type(spheremesh), intent(in) self)
Definition at line 530 of file SphereMesh2.f90.
References planemeshmodule::ccwedgesandparticlesaroundpanel(), planemeshmodule::maximumlagrangianparametervariation(), and spheregeommodule::spheretricenter().
real(kreal) function, public spheremeshmodule::maximumtracermass (type(spheremesh), intent(in) self, integer(kint), intent(in) tracerID)
Definition at line 480 of file SphereMesh2.f90.
References planemeshmodule::maximumtracermass().
real(kreal) function, public spheremeshmodule::maximumtracervariation (type(spheremesh), intent(in) self, integer(kint), intent(in) tracerID)
Definition at line 488 of file SphereMesh2.f90.
References planemeshmodule::maximumtracervariation().
real(kreal) function, public spheremeshmodule::maximumvorticityvariation (type(spheremesh), intent(in) self)
Definition at line 507 of file SphereMesh2.f90.
References planemeshmodule::maximumvorticityvariation().
subroutine, public spheremeshmodule::renormalize (type(spheremesh), intent(inout) self)
Definition at line 226 of file SphereMesh2.f90.
References panelsmodule::getpanelkind().
subroutine, public spheremeshmodule::resetspherearea (type(spheremesh), intent(inout) self)
Definition at line 256 of file SphereMesh2.f90.
real(kreal) function, public spheremeshmodule::totalabsvort (type(spheremesh), intent(in) self)
Definition at line 346 of file SphereMesh2.f90.
real(kreal) function, public spheremeshmodule::totalenstrophy (type(spheremesh), intent(in) self)
Definition at line 406 of file SphereMesh2.f90.
Referenced by bvegaussvort(), lambtest(), reversibledipolesmain(), rh4wave(), and twodipolesmain().
real(kreal) function, public spheremeshmodule::totalmass (type(spheremesh), intent(in) self, integer(kint), intent(in) tracerNumber)
Definition at line 329 of file SphereMesh2.f90.
Referenced by bvegaussvort(), gaussianhillsadvection(), gaussianhillsadvectiondirect(), kentcascadeadvection(), movingvorticesadvection(), and planerotateadvection().
real(kreal) function, public spheremeshmodule::totalrelvort (type(spheremesh), intent(in) self)
Definition at line 389 of file SphereMesh2.f90.
The documentation for this module was generated from the following file:
SphereMesh2.f90