bvesetupmodule Module Reference
Public Member Functions
subroutine, public initsolidbodyrotation (solidBody, rotRate)
subroutine, public setsolidbodyrotationonmesh (aMesh, solidBody)
subroutine, public initsinglegaussianvortex (gaussVort, lat0, lon0, bb, maxVal)
subroutine, public initdecayingvortices (decayingVorts)
subroutine, public setdecayingvorticesonmesh (aMesh, decayingVorts)
subroutine, public setsinglegaussianvortexonmesh (aMesh, gaussVort)
subroutine, public initrh4wave (rh4Wave, alpha, amplitude)
subroutine, public setrh4waveonmesh (aMesh, rhWave)
subroutine, public nullvorticity (aMesh, nullVort)
real(kreal) function, public rh54vorticity (xyz, alpha, amp)
real(kreal) function, public legendre54 (z)
Public Attributes
real(kreal), save, public,
*
protected gauss_const = 0.0_kreal
integer(kint), parameter, public solid_body_nint = 0
integer(kint), parameter, public solid_body_nreal = 1
integer(kint), parameter, public single_vortex_nint = 0
integer(kint), parameter, public single_vortex_nreal = 4
integer(kint), parameter, public rh4_nint = 0
integer(kint), parameter, public rh4_nreal = 2
integer(kint), parameter, public decaying_vort_nint =0
integer(kint), parameter, public decaying_vort_nreal =0
Detailed Description
Definition at line 1 of file BVEVorticity.f90.
Member Function/Subroutine Documentation
subroutine, public bvesetupmodule::initdecayingvortices (type(bvesetup), intent(inout) decayingVorts)
Definition at line 172 of file BVEVorticity.f90.
subroutine, public bvesetupmodule::initrh4wave (type(bvesetup), intent(inout) rh4Wave, real(kreal), intent(in) alpha, real(kreal), intent(in) amplitude)
Definition at line 268 of file BVEVorticity.f90.
References rh4wave().
Referenced by rh4wave().
subroutine, public bvesetupmodule::initsinglegaussianvortex (type(bvesetup), intent(inout) gaussVort, real(kreal), intent(in) lat0, real(kreal), intent(in) lon0, real(kreal), intent(in) bb, real(kreal), intent(in) maxVal)
Definition at line 163 of file BVEVorticity.f90.
Referenced by bvegaussvort().
subroutine, public bvesetupmodule::initsolidbodyrotation (type(bvesetup), intent(inout) solidBody, real(kreal), intent(in) rotRate)
Definition at line 126 of file BVEVorticity.f90.
Referenced by bvesolidbody().
real(kreal) function, public bvesetupmodule::legendre54 (real(kreal), intent(in) z)
Definition at line 351 of file BVEVorticity.f90.
Referenced by rh4wave(), and rh54vorticity().
subroutine, public bvesetupmodule::nullvorticity (type(spheremesh), intent(inout) aMesh, type(bvesetup), intent(in) nullVort)
Definition at line 304 of file BVEVorticity.f90.
Referenced by gaussianhillsadvection(), gaussianhillsadvectiondirect(), kentcascadeadvection(), movingvorticesadvection(), and planerotateadvection().
real(kreal) function, public bvesetupmodule::rh54vorticity (real(kreal), dimension(3), intent(in) xyz, real(kreal), intent(in) alpha, real(kreal), intent(in) amp)
Definition at line 345 of file BVEVorticity.f90.
References legendre54().
Referenced by rh4wave(), and setrh4waveonmesh().
subroutine, public bvesetupmodule::setdecayingvorticesonmesh (type(spheremesh), intent(inout) aMesh, type(bvesetup), intent(in) decayingVorts)
Definition at line 176 of file BVEVorticity.f90.
subroutine, public bvesetupmodule::setrh4waveonmesh (type(spheremesh), intent(inout) aMesh, type(bvesetup), intent(in) rhWave)
Definition at line 275 of file BVEVorticity.f90.
References rh54vorticity().
Referenced by rh4wave().
subroutine, public bvesetupmodule::setsinglegaussianvortexonmesh (type(spheremesh), intent(inout) aMesh, type(bvesetup), intent(in) gaussVort)
Definition at line 216 of file BVEVorticity.f90.
Referenced by bvegaussvort().
subroutine, public bvesetupmodule::setsolidbodyrotationonmesh (type(spheremesh), intent(inout) aMesh, type(bvesetup), intent(in) solidBody)
Definition at line 138 of file BVEVorticity.f90.
Referenced by bvesolidbody().
Member Data Documentation
integer(kint), parameter, public bvesetupmodule::decaying_vort_nint =0
Definition at line 54 of file BVEVorticity.f90.
integer(kint), parameter, public bvesetupmodule::decaying_vort_nreal =0
Definition at line 54 of file BVEVorticity.f90.
real(kreal), save, public, protected bvesetupmodule::gauss_const = 0.0_kreal
Definition at line 50 of file BVEVorticity.f90.
integer(kint), parameter, public bvesetupmodule::rh4_nint = 0
Definition at line 53 of file BVEVorticity.f90.
integer(kint), parameter, public bvesetupmodule::rh4_nreal = 2
Definition at line 53 of file BVEVorticity.f90.
integer(kint), parameter, public bvesetupmodule::single_vortex_nint = 0
Definition at line 52 of file BVEVorticity.f90.
integer(kint), parameter, public bvesetupmodule::single_vortex_nreal = 4
Definition at line 52 of file BVEVorticity.f90.
integer(kint), parameter, public bvesetupmodule::solid_body_nint = 0
Definition at line 51 of file BVEVorticity.f90.
integer(kint), parameter, public bvesetupmodule::solid_body_nreal = 1
Definition at line 51 of file BVEVorticity.f90.
The documentation for this module was generated from the following file:
BVEVorticity.f90