planetracermodule Module Reference
Public Member Functions
subroutine, public nulltracer (aMesh, self)
subroutine, public initthreetracers (self, tracerID)
subroutine, public setthreetracersonmesh (aMesh, self)
real(kreal) function, public threetracers (xy)
subroutine, public initgaussianhill (self, tracerID, xCent, yCent, betaSq, amp)
subroutine, public setgaussianhillonmesh (aMesh, self)
real(kreal) function, public gaussianhill (xy, xcent, ycent, betasq, amp)
subroutine, public initslottedcylinder (self, tracerID, xcent, ycent, r, slotL, slotR, slotTop)
subroutine, public setslottedcylinderonmesh (aMesh, self)
real(kreal) function, public slottedcylinder (xy, xcent, ycent, r, slotL, slotR, slotTop)
subroutine, public initdipoleidtracer (self, xc1, yc1, rad1, xc2, yc2, rad2, tracerID)
real(kreal) function, public dipoleid (xy, xc1, yc1, rad1, xc2, yc2, rad2)
subroutine, public setdipoleidtraceronmesh (aMesh, tsetup)
Detailed Description
Definition at line 1 of file PlaneTracer.f90.
Member Function/Subroutine Documentation
real(kreal) function, public planetracermodule::dipoleid (real(kreal), dimension(2), intent(in) xy, real(kreal), intent(in) xc1, real(kreal), intent(in) yc1, real(kreal), intent(in) rad1, real(kreal), intent(in) xc2, real(kreal), intent(in) yc2, real(kreal), intent(in) rad2)
Definition at line 310 of file PlaneTracer.f90.
Referenced by setdipoleidtraceronmesh().
real(kreal) function, public planetracermodule::gaussianhill (real(kreal), dimension(2), intent(in) xy, real(kreal), intent(in) xcent, real(kreal), intent(in) ycent, real(kreal), intent(in) betasq, real(kreal), intent(in) amp)
Definition at line 224 of file PlaneTracer.f90.
Referenced by setgaussianhillonmesh().
subroutine, public planetracermodule::initdipoleidtracer (type(tracersetup), intent(inout) self, real(kreal), intent(in) xc1, real(kreal), intent(in) yc1, real(kreal), intent(in) rad1, real(kreal), intent(in) xc2, real(kreal), intent(in) yc2, real(kreal), intent(in) rad2, integer(kint), intent(in) tracerID)
Definition at line 294 of file PlaneTracer.f90.
Referenced by reversibledipolesmain(), and twodipolesmain().
subroutine, public planetracermodule::initgaussianhill (type(tracersetup), intent(inout) self, integer(kint), intent(in) tracerID, real(kreal), intent(in) xCent, real(kreal), intent(in) yCent, real(kreal), intent(in) betaSq, real(kreal), intent(in) amp)
Definition at line 181 of file PlaneTracer.f90.
subroutine, public planetracermodule::initslottedcylinder (type(tracersetup), intent(inout) self, integer(kint), intent(in) tracerID, real(kreal), intent(in) xcent, real(kreal), intent(in) ycent, real(kreal), intent(in) r, real(kreal), intent(in) slotL, real(kreal), intent(in) slotR, real(kreal), intent(in) slotTop)
Definition at line 230 of file PlaneTracer.f90.
subroutine, public planetracermodule::initthreetracers (type(tracersetup), intent(inout) self, integer(kint), intent(in) tracerID)
Definition at line 119 of file PlaneTracer.f90.
Referenced by planerotateadvection().
subroutine, public planetracermodule::nulltracer (type(planemesh), intent(inout) aMesh, type(tracersetup), intent(in) self)
Definition at line 114 of file PlaneTracer.f90.
Referenced by lambtest(), planeunittest(), and rh4wave().
subroutine, public planetracermodule::setdipoleidtraceronmesh (type(planemesh), intent(inout) aMesh, type(tracersetup), intent(in) tsetup)
Definition at line 325 of file PlaneTracer.f90.
References dipoleid().
Referenced by reversibledipolesmain(), and twodipolesmain().
subroutine, public planetracermodule::setgaussianhillonmesh (type(planemesh), intent(inout) aMesh, type(tracersetup), intent(in) self)
Definition at line 195 of file PlaneTracer.f90.
References gaussianhill().
subroutine, public planetracermodule::setslottedcylinderonmesh (type(planemesh), intent(inout) aMesh, type(tracersetup), intent(in) self)
Definition at line 246 of file PlaneTracer.f90.
References slottedcylinder().
subroutine, public planetracermodule::setthreetracersonmesh (type(planemesh), intent(inout) aMesh, type(tracersetup), intent(in) self)
Definition at line 127 of file PlaneTracer.f90.
References threetracers().
Referenced by planerotateadvection().
real(kreal) function, public planetracermodule::slottedcylinder (real(kreal), dimension(2), intent(in) xy, real(kreal), intent(in) xcent, real(kreal), intent(in) ycent, real(kreal), intent(in) r, real(kreal), intent(in) slotL, real(kreal), intent(in) slotR, real(kreal), intent(in) slotTop)
Definition at line 271 of file PlaneTracer.f90.
Referenced by setslottedcylinderonmesh().
real(kreal) function, public planetracermodule::threetracers (real(kreal), dimension(2), intent(in) xy)
Definition at line 150 of file PlaneTracer.f90.
Referenced by setthreetracersonmesh().
The documentation for this module was generated from the following file:
PlaneTracer.f90