ssrfpackinterfacemodule Module Reference
Public Member Functions
subroutine, public setsigmatol (self, newTol)
subroutine, public setsourcelagrangianparameter (self, delTri)
subroutine, public setsourcetracer (self, delTri)
subroutine, public setsourceabsvort (self, delTri)
subroutine, public setsourcerelvort (self, delTri)
subroutine, public setsourcekineticenergy (self, delTri)
real(kreal) function,
*
dimension(3), public interpolatevector (xyz, self, delTri)
real(kreal) function, public interpolatescalar (xyz, self, delTri)
real(kreal) function, public interpolatetracer (xyz, self, delTri, tracerID)
Public Attributes
integer(kint), parameter, public sigma_flag = 1
integer(kint), parameter, public grad_flag = 1
Detailed Description
Definition at line 1 of file SSRFPACKInterface2.f90.
Member Function/Subroutine Documentation
real(kreal) function, public ssrfpackinterfacemodule::interpolatescalar (real(kreal), dimension(3), intent(in) xyz, type(ssrfpackdata), intent(in) self, type(stripackdata), intent(in) delTri)
Definition at line 607 of file SSRFPACKInterface2.f90.
References intrc1().
Referenced by sphereremeshmodule::directremesh(), sphereremeshmodule::lagrangianremeshtoreference(), latlonoutputmodule::lloutputmatlab(), and ssrfpackapproximations().
real(kreal) function, public ssrfpackinterfacemodule::interpolatetracer (real(kreal), dimension(3), intent(in) xyz, type(ssrfpackdata), intent(in) self, type(stripackdata), intent(in) delTri, integer(kint), intent(in) tracerID)
Definition at line 627 of file SSRFPACKInterface2.f90.
References intrc1().
Referenced by sphereremeshmodule::directremesh(), sphereremeshmodule::lagrangianremeshtoreference(), and latlonoutputmodule::lloutputmatlab().
real(kreal) function, dimension(3), public ssrfpackinterfacemodule::interpolatevector (real(kreal), dimension(3), intent(in) xyz, type(ssrfpackdata), intent(in) self, type(stripackdata), intent(in) delTri)
Definition at line 576 of file SSRFPACKInterface2.f90.
References intrc1().
Referenced by refineremeshmodule::initialrefinement(), sphereremeshmodule::lagrangianremeshtoreference(), and latlonoutputmodule::lloutputmatlab().
subroutine, public ssrfpackinterfacemodule::setsigmatol (type(ssrfpackdata), intent(inout) self, real(kreal), intent(in) newTol)
Definition at line 200 of file SSRFPACKInterface2.f90.
Referenced by refineremeshmodule::initialrefinement().
subroutine, public ssrfpackinterfacemodule::setsourceabsvort (type(ssrfpackdata), intent(inout) self, type(stripackdata), intent(in) delTri)
Definition at line 416 of file SSRFPACKInterface2.f90.
References getsig(), and gradl().
Referenced by sphereremeshmodule::directremesh(), and latlonoutputmodule::lloutputmatlab().
subroutine, public ssrfpackinterfacemodule::setsourcekineticenergy (type(ssrfpackdata), intent(inout) self, type(stripackdata), intent(in) delTri)
Definition at line 508 of file SSRFPACKInterface2.f90.
References getsig(), and gradl().
Referenced by latlonoutputmodule::lloutputmatlab().
subroutine, public ssrfpackinterfacemodule::setsourcelagrangianparameter (type(ssrfpackdata), intent(inout) self, type(stripackdata), intent(in) delTri)
Definition at line 207 of file SSRFPACKInterface2.f90.
References getsig(), and gradl().
Referenced by refineremeshmodule::initialrefinement(), sphereremeshmodule::lagrangianremeshtoreference(), and latlonoutputmodule::lloutputmatlab().
subroutine, public ssrfpackinterfacemodule::setsourcerelvort (type(ssrfpackdata), intent(inout) self, type(stripackdata), intent(in) delTri)
Definition at line 445 of file SSRFPACKInterface2.f90.
References getsig(), and gradl().
Referenced by latlonoutputmodule::lloutputmatlab(), and ssrfpackapproximations().
subroutine, public ssrfpackinterfacemodule::setsourcetracer (type(ssrfpackdata), intent(inout) self, type(stripackdata), intent(in) delTri)
Definition at line 253 of file SSRFPACKInterface2.f90.
References getsig(), and gradl().
Referenced by sphereremeshmodule::directremesh(), and latlonoutputmodule::lloutputmatlab().
Member Data Documentation
integer(kint), parameter, public ssrfpackinterfacemodule::grad_flag = 1
Definition at line 63 of file SSRFPACKInterface2.f90.
integer(kint), parameter, public ssrfpackinterfacemodule::sigma_flag = 1
Definition at line 63 of file SSRFPACKInterface2.f90.
The documentation for this module was generated from the following file:
SSRFPACKInterface2.f90