swedirectsummodule Module Reference
Public Member Functions
subroutine, public swerk4timestep (self, aMesh, dt, procRank, nProcs)
subroutine, public setvelocitysmoothingparameter (newSmooth)
Public Attributes
real(kreal), save, public,
*
protected velocity_smooth = 0.01_kreal
Detailed Description
Definition at line 1 of file SWEDirectSum.f90.
Member Function/Subroutine Documentation
subroutine, public swedirectsummodule::setvelocitysmoothingparameter (real(kreal), intent(in) newSmooth)
Definition at line 1081 of file SWEDirectSum.f90.
References gradl().
subroutine, public swedirectsummodule::swerk4timestep (type(swerk4data), intent(inout) self, type(spheremesh), intent(inout) aMesh, real(kreal), intent(in) dt, integer(kint), intent(in) procRank, integer(kint), intent(in) nProcs)
Definition at line 518 of file SWEDirectSum.f90.
References panelsmodule::scatterpanels(), stripackinterfacemodule::updatenodepositions(), and advectionmodule::zerork4().
Referenced by nonlinearsteadyswe().
Member Data Documentation
real(kreal), save, public, protected swedirectsummodule::velocity_smooth = 0.01_kreal
Definition at line 43 of file SWEDirectSum.f90.
The documentation for this module was generated from the following file:
SWEDirectSum.f90