planegeommodule Module Reference
Public Member Functions
real(kreal) function distance (xyA, xyB)
real(kreal) function, dimension(2) midpoint (xyA, xyB)
real(kreal) function, dimension(2) tricentroid (xyA, xyB, xyC)
real(kreal) function, dimension(2) quadcentroid (xyA, xyB, xyC, xyD)
real(kreal) function triarea (xA, xB, xC)
Detailed Description
Definition at line 1 of file PlaneGeometry.f90.
Member Function/Subroutine Documentation
real(kreal) function planegeommodule::distance (real(kreal), dimension(2), intent(in) xyA, real(kreal), dimension(2), intent(in) xyB)
Definition at line 30 of file PlaneGeometry.f90.
Referenced by planemeshmodule::dividepanel().
real(kreal) function, dimension(2) planegeommodule::midpoint (real(kreal), dimension(2), intent(in) xyA, real(kreal), dimension(2), intent(in) xyB)
Definition at line 36 of file PlaneGeometry.f90.
Referenced by planemeshmodule::dividepanel().
real(kreal) function, dimension(2) planegeommodule::quadcentroid (real(kreal), dimension(2), intent(in) xyA, real(kreal), dimension(2), intent(in) xyB, real(kreal), dimension(2), intent(in) xyC, real(kreal), dimension(2), intent(in) xyD)
Definition at line 48 of file PlaneGeometry.f90.
Referenced by planemeshmodule::dividepanel(), and planemeshmodule::initializerectangle().
real(kreal) function planegeommodule::triarea (real(kreal), dimension(2), intent(in) xA, real(kreal), dimension(2), intent(in) xB, real(kreal), dimension(2), intent(in) xC)
Definition at line 54 of file PlaneGeometry.f90.
Referenced by planemeshmodule::dividepanel().
real(kreal) function, dimension(2) planegeommodule::tricentroid (real(kreal), dimension(2), intent(in) xyA, real(kreal), dimension(2), intent(in) xyB, real(kreal), dimension(2), intent(in) xyC)
Definition at line 42 of file PlaneGeometry.f90.
The documentation for this module was generated from the following file:
PlaneGeometry.f90