sphereremeshmodule Module Reference
Data Types
interface SetVorticityOnMesh
Public Member Functions
subroutine, public lagrangianremeshtoreference (aMesh, reference, remesh)
subroutine, public directremesh (aMesh, remesh)
Public Attributes
logical(klog), save loginit = .FALSE.
Detailed Description
Definition at line 1 of file SphereRemesh.f90.
Member Function/Subroutine Documentation
subroutine, public sphereremeshmodule::directremesh (type(spheremesh), intent(inout) aMesh, type(remeshsetup), intent(in) remesh)
Definition at line 1087 of file SphereRemesh.f90.
References planemeshmodule::ccwedgesandparticlesaroundpanel(), planemeshmodule::dividepanel(), ssrfpackinterfacemodule::interpolatescalar(), ssrfpackinterfacemodule::interpolatetracer(), ssrfpackinterfacemodule::setsourceabsvort(), and ssrfpackinterfacemodule::setsourcetracer().
Referenced by gaussianhillsadvectiondirect().
subroutine, public sphereremeshmodule::lagrangianremeshtoreference (type(spheremesh), intent(inout) aMesh, type(referencesphere), intent(in) reference, type(remeshsetup), intent(in) remesh)
Definition at line 814 of file SphereRemesh.f90.
References planemeshmodule::dividepanel(), ssrfpackinterfacemodule::interpolatescalar(), ssrfpackinterfacemodule::interpolatetracer(), ssrfpackinterfacemodule::interpolatevector(), and ssrfpackinterfacemodule::setsourcelagrangianparameter().
Referenced by gaussianhillsadvection(), kentcascadeadvection(), movingvorticesadvection(), and rh4wave().
Member Data Documentation
logical(klog), save sphereremeshmodule::loginit = .FALSE.
Definition at line 122 of file SphereRemesh.f90.
The documentation for this module was generated from the following file:
SphereRemesh.f90