refineremeshmodule Module Reference
Data Types
interface SetVorticityOnMesh
Public Member Functions
subroutine, public initialrefinement (aMesh, refineTracer, updateTracerOnMesh, tracerDef, refineRelVort, updateVorticityOnMesh, vortDef)
subroutine, public setrelativetracertols (aMesh, tracerRefine)
subroutine, public setrelativevorticitytols (aMesh, vortRefine)
subroutine, public setrelativeflowmaptol (amesh, flowmapRefine)
subroutine, public flagpanelsfortracermaxrefinement (refineFlag, aMesh, refineTracer, startIndex)
subroutine, public flagpanelsforcirculationrefinement (refineFlag, aMesh, refineRelVort, startIndex)
subroutine, public flagpanelsfortracervariationrefinement (refineFlag, aMesh, refineTracer, startIndex)
subroutine, public flagpanelsforrelvortvariationrefinement (refineFlag, aMesh, refineRelVort, startIndex)
subroutine, public flagpanelsforflowmaprefinement (refineFlag, aMesh, refineFlowMap, startIndex)
subroutine, public flagpanelsatrefinementboundaries (refineFlag, aMesh)
Public Attributes
integer(kint), parameter, public null_refine = 70
integer(kint), parameter, public tracer_refine = 71
integer(kint), parameter, public relvort_refine = 72
integer(kint), parameter, public flowmap_refine = 73
logical(klog), save loginit = .FALSE.
Detailed Description
Definition at line 1 of file RefineRemesh2.f90.
Member Function/Subroutine Documentation
subroutine, public refineremeshmodule::flagpanelsatrefinementboundaries (logical(klog), dimension(:), intent(inout) refineFlag, type(spheremesh), intent(in) aMesh)
Definition at line 930 of file RefineRemesh2.f90.
Referenced by initialrefinement().
subroutine, public refineremeshmodule::flagpanelsforcirculationrefinement (logical(klog), dimension(:), intent(inout) refineFlag, type(spheremesh), intent(in) aMesh, type(refinementsetup), intent(in) refineRelVort, integer(kint), intent(in) startIndex)
Definition at line 792 of file RefineRemesh2.f90.
Referenced by initialrefinement().
subroutine, public refineremeshmodule::flagpanelsforflowmaprefinement (logical(klog), dimension(:), intent(inout) refineFlag, type(spheremesh), intent(in) aMesh, type(refinementsetup), intent(in) refineFlowMap, integer(kint), intent(in) startIndex)
Definition at line 886 of file RefineRemesh2.f90.
References planemeshmodule::ccwedgesandparticlesaroundpanel().
subroutine, public refineremeshmodule::flagpanelsforrelvortvariationrefinement (logical(klog), dimension(:), intent(inout) refineFlag, type(spheremesh), intent(in) aMesh, type(refinementsetup), intent(in) refineRelVort, integer(kint), intent(in) startIndex)
Definition at line 850 of file RefineRemesh2.f90.
References planemeshmodule::ccwedgesandparticlesaroundpanel().
Referenced by initialrefinement().
subroutine, public refineremeshmodule::flagpanelsfortracermaxrefinement (logical(klog), dimension(:), intent(inout) refineFlag, type(spheremesh), intent(in) aMesh, type(refinementsetup), intent(in) refineTracer, integer(kint), intent(in) startIndex)
Definition at line 771 of file RefineRemesh2.f90.
Referenced by initialrefinement().
subroutine, public refineremeshmodule::flagpanelsfortracervariationrefinement (logical(klog), dimension(:), intent(inout) refineFlag, type(spheremesh), intent(in) aMesh, type(refinementsetup), intent(in) refineTracer, integer(kint), intent(in) startIndex)
Definition at line 814 of file RefineRemesh2.f90.
References planemeshmodule::ccwedgesandparticlesaroundpanel().
subroutine, public refineremeshmodule::initialrefinement (type(spheremesh), intent(inout) aMesh, type(refinementsetup), intent(in) refineTracer, procedure(settraceronmesh) updateTracerOnMesh, type(tracersetup), intent(in) tracerDef, type(refinementsetup), intent(in) refineRelVort, procedure(setvorticityonmesh) updateVorticityOnMesh, type(bvesetup), intent(in) vortDef)
Definition at line 158 of file RefineRemesh2.f90.
References stripackinterfacemodule::delaunaytriangulation(), planemeshmodule::dividepanel(), flagpanelsatrefinementboundaries(), flagpanelsforcirculationrefinement(), flagpanelsforrelvortvariationrefinement(), flagpanelsfortracermaxrefinement(), ssrfpackinterfacemodule::interpolatevector(), ssrfpackinterfacemodule::setsigmatol(), and ssrfpackinterfacemodule::setsourcelagrangianparameter().
Referenced by bvegaussvort(), bvesolidbody(), gaussianhillsadvection(), gaussianhillsadvectiondirect(), kentcascadeadvection(), lambtest(), movingvorticesadvection(), planerotateadvection(), planeunittest(), reversibledipolesmain(), rh4wave(), and twodipolesmain().
subroutine, public refineremeshmodule::setrelativeflowmaptol (type(spheremesh), intent(in) amesh, type(refinementsetup), intent(inout) flowmapRefine)
Definition at line 721 of file RefineRemesh2.f90.
References planemeshmodule::maxx(), planemeshmodule::maxy(), planemeshmodule::minx(), and planemeshmodule::miny().
Referenced by bvegaussvort().
subroutine, public refineremeshmodule::setrelativetracertols (type(spheremesh), intent(in) aMesh, type(refinementsetup), intent(inout) tracerRefine)
Definition at line 629 of file RefineRemesh2.f90.
Referenced by bvegaussvort().
subroutine, public refineremeshmodule::setrelativevorticitytols (type(spheremesh), intent(in) aMesh, type(refinementsetup), intent(inout) vortRefine)
Definition at line 677 of file RefineRemesh2.f90.
Referenced by bvegaussvort().
Member Data Documentation
integer(kint), parameter, public refineremeshmodule::flowmap_refine = 73
Definition at line 47 of file RefineRemesh2.f90.
logical(klog), save refineremeshmodule::loginit = .FALSE.
Definition at line 103 of file RefineRemesh2.f90.
integer(kint), parameter, public refineremeshmodule::null_refine = 70
Definition at line 47 of file RefineRemesh2.f90.
integer(kint), parameter, public refineremeshmodule::relvort_refine = 72
Definition at line 47 of file RefineRemesh2.f90.
integer(kint), parameter, public refineremeshmodule::tracer_refine = 71
Definition at line 47 of file RefineRemesh2.f90.
The documentation for this module was generated from the following file:
RefineRemesh2.f90