panelsmodule Module Reference
Public Member Functions
integer(kint) function, public getpanelkind (self)
integer(kint) function, public getproblemkind (self)
subroutine, public gatherpanels (self, activePanels, activeMap, passivePanels, passiveMap)
subroutine, public scatterpanels (self, activePanels, activeMap, passivePanels, passiveMap)
integer(kint) function, public panelmax (panelKind, maxNest)
Detailed Description
Definition at line 1 of file Panels.f90.
Member Function/Subroutine Documentation
subroutine, public panelsmodule::gatherpanels (type(panels), intent(in) self, type(panels), intent(inout) activePanels, integer(kint), dimension(:), intent(inout) activeMap, type(panels), intent(inout) passivePanels, integer(kint), dimension(:), intent(inout) passiveMap)
Definition at line 490 of file Panels.f90.
integer(kint) function, public panelsmodule::getpanelkind (type(panels), intent(in) self)
Definition at line 458 of file Panels.f90.
Referenced by spheremeshmodule::ccwedgesandparticlesaroundpanel(), spheremeshmodule::dividepanel(), spheremeshmodule::findadjacentpanels(), panelmax(), spheremeshmodule::renormalize(), and vtkoutputmodule::vtkoutput().
integer(kint) function, public panelsmodule::getproblemkind (type(panels), intent(in) self)
Definition at line 477 of file Panels.f90.
integer(kint) function, public panelsmodule::panelmax (integer(kint), intent(in) panelKind, integer(kint), intent(in) maxNest)
Definition at line 568 of file Panels.f90.
References getpanelkind().
subroutine, public panelsmodule::scatterpanels (type(panels), intent(inout) self, type(panels), intent(in) activePanels, integer(kint), dimension(:), intent(in) activeMap, type(panels), intent(in) passivePanels, integer(kint), dimension(:), intent(in) passiveMap)
Definition at line 544 of file Panels.f90.
Referenced by advectionmodule::advectionrk4timestep(), bvedirectsummodule::bverk4timestep(), planedirectsummodule::rk4timestepincompressibleadvection(), planedirectsummodule::rk4timestepnorotation(), and swedirectsummodule::swerk4timestep().
The documentation for this module was generated from the following file:
Panels.f90