spheregeommodule Module Reference
Data Types
interface latitude
interface longitude
interface spherearclength
interface spheredistance
interface spheretriarea
Public Member Functions
real(kreal) function chorddistance (xyzA, xyzB)
real(kreal) function spheredistancevector (xyzA, xyzB)
real(kreal) function spheredistancecomponents (xA, yA, zA, xB, yB, zB)
real(kreal) function spherearclengthvector (xyzA, xyzB)
real(kreal) function spherearclengthcomponents (xA, yA, zA, xB, yB, zB)
real(kreal) function, dimension(3) latunitvector (xyz)
real(kreal) function, dimension(3) lonunitvector (xyz)
real(kreal) function, dimension(3) spheremidpoint (xyzA, xyzB)
real(kreal) function, dimension(3) spheretricenter (xyzA, xyzB, xyzC)
real(kreal) function, dimension(3) spherequadcenter (xyzA, xyzB, xyzC, xyzD)
real(kreal) function spheretriareavector (xyzA, xyzB, xyzC)
real(kreal) function spheretriareacomponents (xa, ya, za, xb, yb, zb, xc, yc, zc)
real(kreal) function planetriarea (xyzA, xyzB, xyzC)
real(kreal) function longitudevector (xyz)
real(kreal) function longitudecomponents (x, y, z)
real(kreal) function longitudecomponents2 (x, y)
real(kreal) function latitudevector (xyz)
real(kreal) function latitudecomponents (x, y, z)
real(kreal) function atan4 (y, x)
real(kreal) function crossmagnitude (xyzA, xyzB)
real(kreal) function, dimension(3) crossproduct (xyzA, xyzB)
real(kreal) function determinant (xA, xB, xC)
real(kreal) function, dimension(3) randomspherepoint ()
subroutine normalizepositionvectors (xyz)
Detailed Description
Definition at line 1 of file SphereGeom3.f90.
Member Function/Subroutine Documentation
real(kreal) function spheregeommodule::atan4 (real(kreal), intent(in) y, real(kreal), intent(in) x)
Definition at line 300 of file SphereGeom3.f90.
Referenced by longitudecomponents(), longitudecomponents2(), longitudevector(), and advectionmodule::movingvorticesvelocity().
real(kreal) function spheregeommodule::chorddistance (real(kreal), dimension(3), intent(in) xyzA, real(kreal), dimension(3), intent(in) xyzB)
Definition at line 57 of file SphereGeom3.f90.
real(kreal) function spheregeommodule::crossmagnitude (real(kreal), dimension(3), intent(in) xyzA, real(kreal), dimension(3), intent(in) xyzB)
Definition at line 338 of file SphereGeom3.f90.
Referenced by planetriarea().
real(kreal) function, dimension(3) spheregeommodule::crossproduct (real(kreal), dimension(3), intent(in) xyzA, real(kreal), dimension(3), intent(in) xyzB)
Definition at line 348 of file SphereGeom3.f90.
Referenced by determinant().
real(kreal) function spheregeommodule::determinant (real(kreal), dimension(3), intent(in) xA, real(kreal), dimension(3), intent(in) xB, real(kreal), dimension(3), intent(in) xC)
Definition at line 357 of file SphereGeom3.f90.
References crossproduct().
real(kreal) function spheregeommodule::latitudecomponents (real(kreal), intent(in) x, real(kreal), intent(in) y, real(kreal), intent(in) z)
Definition at line 293 of file SphereGeom3.f90.
References spheregeommodule::latitude::latitudecomponents().
real(kreal) function spheregeommodule::latitudevector (real(kreal), dimension(3), intent(in) xyz)
Definition at line 285 of file SphereGeom3.f90.
References spheregeommodule::latitude::latitudevector().
real(kreal) function, dimension(3) spheregeommodule::latunitvector (real(kreal), dimension(3), intent(in) xyz)
Definition at line 145 of file SphereGeom3.f90.
Referenced by latlonoutputmodule::lloutputmatlab().
real(kreal) function spheregeommodule::longitudecomponents (real(kreal), intent(in) x, real(kreal), intent(in) y, real(kreal), intent(in) z)
Definition at line 271 of file SphereGeom3.f90.
References atan4(), and spheregeommodule::longitude::longitudecomponents().
real(kreal) function spheregeommodule::longitudecomponents2 (real(kreal), intent(in) x, real(kreal), intent(in) y)
Definition at line 278 of file SphereGeom3.f90.
References atan4(), and spheregeommodule::longitude::longitudecomponents2().
real(kreal) function spheregeommodule::longitudevector (real(kreal), dimension(3), intent(in) xyz)
Definition at line 263 of file SphereGeom3.f90.
References atan4(), and spheregeommodule::longitude::longitudevector().
real(kreal) function, dimension(3) spheregeommodule::lonunitvector (real(kreal), dimension(3), intent(in) xyz)
Definition at line 161 of file SphereGeom3.f90.
Referenced by latlonoutputmodule::lloutputmatlab().
subroutine spheregeommodule::normalizepositionvectors (real(kreal), dimension(:,:), intent(inout) xyz)
Definition at line 388 of file SphereGeom3.f90.
real(kreal) function spheregeommodule::planetriarea (real(kreal), dimension(3), intent(in) xyzA, real(kreal), dimension(3), intent(in) xyzB, real(kreal), dimension(3), intent(in) xyzC)
Definition at line 255 of file SphereGeom3.f90.
References crossmagnitude().
real(kreal) function, dimension(3) spheregeommodule::randomspherepoint ()
Definition at line 369 of file SphereGeom3.f90.
real(kreal) function spheregeommodule::spherearclengthcomponents (real(kreal), intent(in) xA, real(kreal), intent(in) yA, real(kreal), intent(in) zA, real(kreal), intent(in) xB, real(kreal), intent(in) yB, real(kreal), intent(in) zB)
Definition at line 126 of file SphereGeom3.f90.
References spheregeommodule::spherearclength::spherearclengthcomponents().
real(kreal) function spheregeommodule::spherearclengthvector (real(kreal), dimension(3), intent(in) xyzA, real(kreal), dimension(3), intent(in) xyzB)
Definition at line 106 of file SphereGeom3.f90.
References spheregeommodule::spherearclength::spherearclengthvector().
real(kreal) function spheregeommodule::spheredistancecomponents (real(kreal), intent(in) xA, real(kreal), intent(in) yA, real(kreal), intent(in) zA, real(kreal), intent(in) xB, real(kreal), intent(in) yB, real(kreal), intent(in) zB)
Definition at line 87 of file SphereGeom3.f90.
References spheregeommodule::spheredistance::spheredistancecomponents().
real(kreal) function spheregeommodule::spheredistancevector (real(kreal), dimension(3), intent(in) xyzA, real(kreal), dimension(3), intent(in) xyzB)
Definition at line 66 of file SphereGeom3.f90.
References spheregeommodule::spheredistance::spheredistancevector().
real(kreal) function, dimension(3) spheregeommodule::spheremidpoint (real(kreal), dimension(3), intent(in) xyzA, real(kreal), dimension(3), intent(in) xyzB)
Definition at line 178 of file SphereGeom3.f90.
Referenced by spheremeshmodule::dividepanel().
real(kreal) function, dimension(3) spheregeommodule::spherequadcenter (real(kreal), dimension(3), intent(in) xyzA, real(kreal), dimension(3), intent(in) xyzB, real(kreal), dimension(3), intent(in) xyzC, real(kreal), dimension(3), intent(in) xyzD)
Definition at line 201 of file SphereGeom3.f90.
Referenced by spheremeshmodule::dividepanel(), and spheremeshmodule::findadjacentpanels().
real(kreal) function spheregeommodule::spheretriareacomponents (real(kreal), intent(in) xa, real(kreal), intent(in) ya, real(kreal), intent(in) za, real(kreal), intent(in) xb, real(kreal), intent(in) yb, real(kreal), intent(in) zb, real(kreal), intent(in) xc, real(kreal), intent(in) yc, real(kreal), intent(in) zc)
Definition at line 235 of file SphereGeom3.f90.
References spheregeommodule::spherearclength::spherearclengthcomponents(), and spheregeommodule::spheretriarea::spheretriareacomponents().
real(kreal) function spheregeommodule::spheretriareavector (real(kreal), dimension(3), intent(in) xyzA, real(kreal), dimension(3), intent(in) xyzB, real(kreal), dimension(3), intent(in) xyzC)
Definition at line 213 of file SphereGeom3.f90.
References spheregeommodule::spheretriarea::spheretriareavector().
real(kreal) function, dimension(3) spheregeommodule::spheretricenter (real(kreal), dimension(3), intent(in) xyzA, real(kreal), dimension(3), intent(in) xyzB, real(kreal), dimension(3), intent(in) xyzC)
Definition at line 189 of file SphereGeom3.f90.
Referenced by spheremeshmodule::dividepanel(), and spheremeshmodule::maximumlagrangianparametervariation().
The documentation for this module was generated from the following file:
SphereGeom3.f90