planedirectsummodule Module Reference
Public Member Functions
subroutine, public rk4timestepnorotation (self, aMesh, dt, procRank, nProcs)
subroutine, public rk4timestepincompressibleadvection (self, aMesh, dt, t, procRank, nProcs, velocityFunction)
real(kreal) function,
*
dimension(2), public leveque93 (xy, t)
Public Attributes
real(kreal), save, public,
*
protected velocity_smooth = 0.01_kreal
Detailed Description
Definition at line 1 of file PlaneDirectSum.f90.
Member Function/Subroutine Documentation
real(kreal) function, dimension(2), public planedirectsummodule::leveque93 (real(kreal), dimension(2), intent(in) xy, real(kreal), intent(in) t)
Definition at line 808 of file PlaneDirectSum.f90.
Referenced by planerotateadvection().
subroutine, public planedirectsummodule::rk4timestepincompressibleadvection (type(planerk4directsum), intent(inout) self, type(planemesh), intent(inout) aMesh, real(kreal), intent(in) dt, real(kreal), intent(in) t, integer(kint), intent(in) procRank, integer(kint), intent(in) nProcs, procedure(advectionvelocity) velocityFunction)
Definition at line 480 of file PlaneDirectSum.f90.
References panelsmodule::scatterpanels(), and advectionmodule::zerork4().
Referenced by planerotateadvection().
subroutine, public planedirectsummodule::rk4timestepnorotation (type(planerk4directsum), intent(inout) self, type(planemesh), intent(inout) aMesh, real(kreal), intent(in) dt, integer(kint), intent(in) procRank, integer(kint), intent(in) nProcs)
Definition at line 300 of file PlaneDirectSum.f90.
References panelsmodule::scatterpanels(), and advectionmodule::zerork4().
Referenced by lambtest(), planeunittest(), reversibledipolesmain(), and twodipolesmain().
Member Data Documentation
real(kreal), save, public, protected planedirectsummodule::velocity_smooth = 0.01_kreal
Definition at line 42 of file PlaneDirectSum.f90.
The documentation for this module was generated from the following file:
PlaneDirectSum.f90