planemeshmodule Module Reference
Public Member Functions
subroutine, public initializerectangle (self, xmin, xmax, ymin, ymax, boundaryType)
subroutine, public ccwedgesandparticlesaroundpanel (edgeList, vertlist, nVerts, self, panelIndex)
subroutine, public findadjacentpanels (adjPanels, nAdj, self, panelIndex)
integer(kint) function, public locatepoint (self, xy)
real(kreal) function, public totalarea (self)
real(kreal) function, public gettotalenstrophy (self)
real(kreal) function, public gettotalcirculation (self)
real(kreal) function, public gettotalmass (self, tracerID)
real(kreal) function, public gettotalke (self)
real(kreal) function, public maximumcirculation (self)
real(kreal) function, public maximumtracermass (self, tracerID)
real(kreal) function, public maximumtracervariation (self, tracerID)
real(kreal) function, public maximumvorticityvariation (self)
real(kreal) function, public maximumlagrangianparametervariation (self)
real(kreal) function, public minx (self)
real(kreal) function, public maxx (self)
real(kreal) function, public miny (self)
real(kreal) function, public maxy (self)
subroutine, public dividepanel (self, panelIndex)
Detailed Description
Definition at line 1 of file PlaneMesh.f90.
Member Function/Subroutine Documentation
subroutine, public planemeshmodule::ccwedgesandparticlesaroundpanel (integer(kint), dimension(8), intent(inout) edgeList, integer(kint), dimension(8), intent(inout) vertlist, integer(kint), intent(inout) nVerts, type(planemesh), intent(in) self, integer(kint), intent(in) panelIndex)
Definition at line 353 of file PlaneMesh.f90.
Referenced by spheremeshmodule::countsubtriangles(), sphereremeshmodule::directremesh(), spheremeshmodule::dividepanel(), dividepanel(), findadjacentpanels(), spheremeshmodule::findadjacentpanels(), refineremeshmodule::flagpanelsforflowmaprefinement(), refineremeshmodule::flagpanelsforrelvortvariationrefinement(), refineremeshmodule::flagpanelsfortracervariationrefinement(), spheremeshmodule::maximumlagrangianparametervariation(), planeoutputmodule::outputforvtk(), trivariatequadraticapproximations(), and vtkoutputmodule::vtkoutput().
subroutine, public planemeshmodule::dividepanel (type(planemesh), intent(inout) self, integer(kint), intent(in) panelIndex)
Definition at line 600 of file PlaneMesh.f90.
References ccwedgesandparticlesaroundpanel(), planegeommodule::distance(), findadjacentpanels(), planegeommodule::midpoint(), planegeommodule::quadcentroid(), and planegeommodule::triarea().
Referenced by sphereremeshmodule::directremesh(), initializerectangle(), refineremeshmodule::initialrefinement(), and sphereremeshmodule::lagrangianremeshtoreference().
subroutine, public planemeshmodule::findadjacentpanels (integer(kint), dimension(:), intent(inout) adjPanels, integer(kint), intent(inout) nAdj, type(planemesh), intent(in) self, integer(kint), intent(in) panelIndex)
Definition at line 418 of file PlaneMesh.f90.
References ccwedgesandparticlesaroundpanel().
Referenced by dividepanel(), spheremeshmodule::dividepanel(), and trivariatequadraticapproximations().
real(kreal) function, public planemeshmodule::gettotalcirculation (type(planemesh), intent(in) self)
Definition at line 475 of file PlaneMesh.f90.
Referenced by lambtest(), reversibledipolesmain(), and twodipolesmain().
real(kreal) function, public planemeshmodule::gettotalenstrophy (type(planemesh), intent(in) self)
Definition at line 466 of file PlaneMesh.f90.
Referenced by lambtest(), reversibledipolesmain(), and twodipolesmain().
real(kreal) function, public planemeshmodule::gettotalke (type(planemesh), intent(in) self)
Definition at line 494 of file PlaneMesh.f90.
Referenced by lambtest(), reversibledipolesmain(), and twodipolesmain().
real(kreal) function, public planemeshmodule::gettotalmass (type(planemesh), intent(in) self, integer(kint), intent(in) tracerID)
Definition at line 484 of file PlaneMesh.f90.
Referenced by planerotateadvection().
subroutine, public planemeshmodule::initializerectangle (type(planemesh), intent(inout) self, real(kreal), intent(in) xmin, real(kreal), intent(in) xmax, real(kreal), intent(in) ymin, real(kreal), intent(in) ymax, integer(kint), intent(in) boundaryType)
Definition at line 222 of file PlaneMesh.f90.
References dividepanel(), and planegeommodule::quadcentroid().
Referenced by lambtest(), planerotateadvection(), planeunittest(), reversibledipolesmain(), and twodipolesmain().
integer(kint) function, public planemeshmodule::locatepoint (type(planemesh), intent(in) self, real(kreal), dimension(2), intent(in) xy)
Definition at line 443 of file PlaneMesh.f90.
Referenced by spheremeshmodule::locatepoint().
real(kreal) function, public planemeshmodule::maximumcirculation (type(planemesh), intent(in) self)
Definition at line 508 of file PlaneMesh.f90.
Referenced by converttorelativetolerances(), and spheremeshmodule::maximumcirculation().
real(kreal) function, public planemeshmodule::maximumlagrangianparametervariation (type(planemesh), intent(in) self)
Definition at line 559 of file PlaneMesh.f90.
Referenced by convertfromrelativetolerances(), converttorelativetolerances(), and spheremeshmodule::maximumlagrangianparametervariation().
real(kreal) function, public planemeshmodule::maximumtracermass (type(planemesh), intent(in) self, integer(kint), intent(in) tracerID)
Definition at line 517 of file PlaneMesh.f90.
Referenced by convertfromrelativetolerances(), and spheremeshmodule::maximumtracermass().
real(kreal) function, public planemeshmodule::maximumtracervariation (type(planemesh), intent(in) self, integer(kint), intent(in) tracerID)
Definition at line 527 of file PlaneMesh.f90.
Referenced by convertfromrelativetolerances(), and spheremeshmodule::maximumtracervariation().
real(kreal) function, public planemeshmodule::maximumvorticityvariation (type(planemesh), intent(in) self)
Definition at line 542 of file PlaneMesh.f90.
Referenced by converttorelativetolerances(), and spheremeshmodule::maximumvorticityvariation().
real(kreal) function, public planemeshmodule::maxx (type(planemesh), intent(in) self)
Definition at line 574 of file PlaneMesh.f90.
Referenced by refineremeshmodule::setrelativeflowmaptol().
real(kreal) function, public planemeshmodule::maxy (type(planemesh), intent(in) self)
Definition at line 586 of file PlaneMesh.f90.
Referenced by refineremeshmodule::setrelativeflowmaptol().
real(kreal) function, public planemeshmodule::minx (type(planemesh), intent(in) self)
Definition at line 568 of file PlaneMesh.f90.
Referenced by refineremeshmodule::setrelativeflowmaptol().
real(kreal) function, public planemeshmodule::miny (type(planemesh), intent(in) self)
Definition at line 580 of file PlaneMesh.f90.
Referenced by refineremeshmodule::setrelativeflowmaptol().
real(kreal) function, public planemeshmodule::totalarea (type(planemesh), intent(in) self)
Definition at line 457 of file PlaneMesh.f90.
Referenced by lambtest(), planerotateadvection(), planeunittest(), reversibledipolesmain(), and twodipolesmain().
The documentation for this module was generated from the following file:
PlaneMesh.f90