stripackinterfacemodule Module Reference
Public Member Functions
subroutine, public delaunaytriangulation (self)
subroutine, public updatenodepositions (self, newParticlesX, nParticles, newactivePanelsX, nActive)
Detailed Description
Definition at line 1 of file STRIPACKInterface2.f90.
Member Function/Subroutine Documentation
subroutine, public stripackinterfacemodule::delaunaytriangulation (type(stripackdata), intent(inout) self)
Definition at line 235 of file STRIPACKInterface2.f90.
References trmesh().
Referenced by refineremeshmodule::initialrefinement(), and updatenodepositions().
subroutine, public stripackinterfacemodule::updatenodepositions (type(stripackdata), intent(inout) self, real(kreal), dimension(:,:), intent(in) newParticlesX, integer(kint), intent(in) nParticles, real(kreal), dimension(:,:), intent(in) newactivePanelsX, integer(kint), intent(in) nActive)
Definition at line 284 of file STRIPACKInterface2.f90.
References delaunaytriangulation().
Referenced by swedirectsummodule::swerk4timestep().
The documentation for this module was generated from the following file:
STRIPACKInterface2.f90