bvedirectsummodule Module Reference
Public Member Functions
subroutine, public bverk4timestep (self, aMesh, dt, procRank, nProcs)
Public Attributes
real(kreal), save, public,
*
protected velocity_smooth = 0.01_kreal
Detailed Description
Definition at line 1 of file BVEDirectSum.f90.
Member Function/Subroutine Documentation
subroutine, public bvedirectsummodule::bverk4timestep (type(bverk4data), intent(inout) self, type(spheremesh), intent(inout) aMesh, real(kreal), intent(in) dt, integer(kint), intent(in) procRank, integer(kint), intent(in) nProcs)
Definition at line 311 of file BVEDirectSum.f90.
References panelsmodule::scatterpanels(), and advectionmodule::zerork4().
Referenced by bvegaussvort(), bvesolidbody(), and rh4wave().
Member Data Documentation
real(kreal), save, public, protected bvedirectsummodule::velocity_smooth = 0.01_kreal
Definition at line 41 of file BVEDirectSum.f90.
The documentation for this module was generated from the following file:
BVEDirectSum.f90