planeoutputmodule Module Reference
Public Member Functions
subroutine, public updatefilename (self, newfilename)
subroutine, public outputforvtk (self, aMesh)
subroutine, public outputforncl (self, aMesh)
subroutine, public outputformatlab (self, aMesh)
Detailed Description
Definition at line 1 of file PlaneOutput.f90.
Member Function/Subroutine Documentation
subroutine, public planeoutputmodule::outputformatlab (type(planeoutput), intent(in) self, type(planemesh), intent(in) aMesh)
Definition at line 259 of file PlaneOutput.f90.
subroutine, public planeoutputmodule::outputforncl (type(planeoutput), intent(in) self, type(planemesh), intent(in) aMesh)
Definition at line 253 of file PlaneOutput.f90.
subroutine, public planeoutputmodule::outputforvtk (type(planeoutput), intent(in) self, type(planemesh), intent(in) aMesh)
Definition at line 139 of file PlaneOutput.f90.
References planemeshmodule::ccwedgesandparticlesaroundpanel().
Referenced by lambtest(), planerotateadvection(), planeunittest(), reversibledipolesmain(), and twodipolesmain().
subroutine, public planeoutputmodule::updatefilename (type(planeoutput), intent(inout) self, character(len=*), intent(in) newfilename)
Definition at line 133 of file PlaneOutput.f90.
Referenced by bvegaussvort(), bvesolidbody(), gaussianhillsadvection(), gaussianhillsadvectiondirect(), kentcascadeadvection(), lambtest(), movingvorticesadvection(), nonlinearsteadyswe(), planerotateadvection(), planeunittest(), reversibledipolesmain(), rh4wave(), swedivergenceequationterms(), testcase1(), and twodipolesmain().
The documentation for this module was generated from the following file:
PlaneOutput.f90