planevorticitymodule Module Reference
Public Member Functions
subroutine, public nullvorticity (aMesh, self)
subroutine, public initrankinevortex (self, xCent, yCent, radius, strength)
subroutine, public setrankinevortexonmesh (aMesh, self)
real(kreal) function, public rankinevortex (xy, xyCent, radius, strength)
subroutine, public initlambdipole (self, lambR, U0, xCent, yCent)
subroutine, public setlambdipoleonmesh (aMesh, self)
real(kreal) function, public lambdipole (xy, lambR, U0, xcent, ycent)
subroutine, public inittwodipoles (self, xc1, yc1, rad1, u1, xc2, yc2, rad2, u2)
subroutine, public settwodipolesonmesh (aMesh, self)
real(kreal) function, public twodipoles (xy, xc1, yc1, rad1, u1, xc2, yc2, rad2, u2)
Public Attributes
integer(kint), parameter, public rankine_n_int = 0
integer(kint), parameter, public rankine_n_real = 4
integer(kint), parameter, public lamb_dipole_n_int = 0
integer(kint), parameter, public lamb_dipole_n_real = 4
integer(kint), parameter, public two_dipoles_n_int = 0
integer(kint), parameter, public two_dipoles_n_real = 8
Detailed Description
Definition at line 1 of file PlaneVorticity.f90.
Member Function/Subroutine Documentation
subroutine, public planevorticitymodule::initlambdipole (type(vorticitysetup), intent(inout) self, real(kreal), intent(in) lambR, real(kreal), intent(in) U0, real(kreal), intent(in) xCent, real(kreal), intent(in) yCent)
Definition at line 185 of file PlaneVorticity.f90.
Referenced by lambtest().
subroutine, public planevorticitymodule::initrankinevortex (type(vorticitysetup), intent(inout) self, real(kreal), intent(in) xCent, real(kreal), intent(in) yCent, real(kreal), intent(in) radius, real(kreal), intent(in) strength)
Definition at line 127 of file PlaneVorticity.f90.
Referenced by planeunittest().
subroutine, public planevorticitymodule::inittwodipoles (type(vorticitysetup), intent(inout) self, real(kreal), intent(in) xc1, real(kreal), intent(in) yc1, real(kreal), intent(in) rad1, real(kreal), intent(in) u1, real(kreal), intent(in) xc2, real(kreal), intent(in) yc2, real(kreal), intent(in) rad2, real(kreal), intent(in) u2)
Definition at line 246 of file PlaneVorticity.f90.
Referenced by reversibledipolesmain(), and twodipolesmain().
real(kreal) function, public planevorticitymodule::lambdipole (real(kreal), dimension(2), intent(in) xy, real(kreal), intent(in) lambR, real(kreal), intent(in) U0, real(kreal), intent(in) xcent, real(kreal), intent(in) ycent)
Definition at line 223 of file PlaneVorticity.f90.
References bessj0(), and bessj1().
Referenced by setlambdipoleonmesh(), and twodipoles().
subroutine, public planevorticitymodule::nullvorticity (type(planemesh), intent(inout) aMesh, type(vorticitysetup), intent(in) self)
Definition at line 121 of file PlaneVorticity.f90.
real(kreal) function, public planevorticitymodule::rankinevortex (real(kreal), dimension(2), intent(in) xy, real(kreal), dimension(2), intent(in) xyCent, real(kreal), intent(in) radius, real(kreal), intent(in) strength)
Definition at line 172 of file PlaneVorticity.f90.
Referenced by setrankinevortexonmesh().
subroutine, public planevorticitymodule::setlambdipoleonmesh (type(planemesh), intent(inout) aMesh, type(vorticitysetup), intent(in) self)
Definition at line 200 of file PlaneVorticity.f90.
References lambdipole().
Referenced by lambtest().
subroutine, public planevorticitymodule::setrankinevortexonmesh (type(planemesh), intent(inout) aMesh, type(vorticitysetup), intent(in) self)
Definition at line 142 of file PlaneVorticity.f90.
References rankinevortex().
Referenced by planeunittest().
subroutine, public planevorticitymodule::settwodipolesonmesh (type(planemesh), intent(inout) aMesh, type(vorticitysetup), intent(in) self)
Definition at line 266 of file PlaneVorticity.f90.
References twodipoles().
Referenced by reversibledipolesmain(), and twodipolesmain().
real(kreal) function, public planevorticitymodule::twodipoles (real(kreal), dimension(2), intent(in) xy, real(kreal), intent(in) xc1, real(kreal), intent(in) yc1, real(kreal), intent(in) rad1, real(kreal), intent(in) u1, real(kreal), intent(in) xc2, real(kreal), intent(in) yc2, real(kreal), intent(in) rad2, real(kreal), intent(in) u2)
Definition at line 293 of file PlaneVorticity.f90.
References bessj0(), bessj1(), and lambdipole().
Referenced by settwodipolesonmesh().
Member Data Documentation
integer(kint), parameter, public planevorticitymodule::lamb_dipole_n_int = 0
Definition at line 46 of file PlaneVorticity.f90.
integer(kint), parameter, public planevorticitymodule::lamb_dipole_n_real = 4
Definition at line 46 of file PlaneVorticity.f90.
integer(kint), parameter, public planevorticitymodule::rankine_n_int = 0
Definition at line 46 of file PlaneVorticity.f90.
integer(kint), parameter, public planevorticitymodule::rankine_n_real = 4
Definition at line 46 of file PlaneVorticity.f90.
integer(kint), parameter, public planevorticitymodule::two_dipoles_n_int = 0
Definition at line 46 of file PlaneVorticity.f90.
integer(kint), parameter, public planevorticitymodule::two_dipoles_n_real = 8
Definition at line 46 of file PlaneVorticity.f90.
The documentation for this module was generated from the following file:
PlaneVorticity.f90