SphereMesh module
Combines primitives (particles, edges, and panels) to form spherical mesh object; plus mesh functions / subroutines.
Functions/Subroutines
subroutine, public spheremeshmodule::renormalize (self)
Resets position vector of all particles in SphereMesh object to satisfy x^2 + y^2 + z^2 = R^2.
subroutine, public spheremeshmodule::resetspherearea (self)
Resets area of all panels in SphereMesh.
subroutine, public spheremeshmodule::ccwedgesandparticlesaroundpanel (edgeList, vertList, nVerts, self, panelIndex)
Determines the adjacency information of a panel within a SphereMesh.
real(kreal) function, public spheremeshmodule::totalmass (self, tracerNumber)
Computes the total integral of a tracer over the sphere using midpoint rule quadrature.
real(kreal) function, public spheremeshmodule::totalabsvort (self)
Computes the total integral of a absolute vorticity over the sphere using midpoint rule quadrature.
real(kreal) function, public spheremeshmodule::getrossbynumber (self)
Computes the Rossby number of the current vorticity distribution.
real(kreal) function, public spheremeshmodule::totalrelvort (self)
Computes the total integral of relative vorticity over the sphere using midpoint rule quadrature.
real(kreal) function, public spheremeshmodule::totalenstrophy (self)
Computes the total enstrophy over the sphere using midpoint rule quadrature.
integer(kint) function, public spheremeshmodule::locatepoint (self, xyz)
Locates an arbitrary point on the sphere within a SphereMesh.
real(kreal) function, public spheremeshmodule::maximumcirculation (self)
Finds the maximum magnitude of circulation about any panel in a mesh.
real(kreal) function, public spheremeshmodule::maximumtracermass (self, tracerID)
Finds the maximum amount of tracer mass contained in any panel in a mesh.
real(kreal) function, public spheremeshmodule::maximumtracervariation (self, tracerID)
Finds the maximum variation of a passive tracer over a whole SphereMesh.
real(kreal) function, public spheremeshmodule::maximumvorticityvariation (self)
Finds the maximum variation of a relative vorticiy over a whole SphereMesh.
real(kreal) function, public spheremeshmodule::averagelagrangianparametervariation (self)
Estimates the average edge length of a panel in Lagrangian coordinate space.
real(kreal) function, public spheremeshmodule::maximumlagrangianparametervariation (self)
Finds the maximum Lagrangian coordinate variation over each panel in a SphereMesh.
Detailed Description
Combines primitives (particles, edges, and panels) to form spherical mesh object; plus mesh functions / subroutines.
Author
Peter Bosler, Department of Mathematics, University of Michigan
Meshes may be triangular panels from an icosahedral triangular discretization or quadrilatertal panels from the cubed sphere. The type of panel is set by the panelKind variable. panelKind should be set using the constants defined in NumberKinds3.f90, so panelKind = TRI_PANEL yields a set of triangular panels while panelKind = QUAD_PANEL yields a mesh of quadrilateral panels.
Each root polyhedron (the icosahedron or the cube) is defined as the root of the quadtree panels data structure; users choose a mesh size by defining how many levels the tree should have with the initNest variable. An setting of initNest = 1 will cause each root panel from the initial polyhedron to be refined once, and the quadtree will have two levels, 0 and 1. Typical coarse meshes for the sphere use initNest = 3 for triangles (1280 panels) and initNest = 4 for quadrilaterals (1536) panels. Approximate resolutions of 1 degree are given by setting initNest = 6 for triangles (81920 panels) and initNest = 7 for quadrilaterals (98304 panels).
Users may toggle adaptive refinement via the AMR variable. AMR = 0 turns off adaptive refinement and creates a computation where the number of panels is the same for all time. AMR > 0 turns on AMR, and the number determines the amount of memory allocated. AMR = 1 creates reserves enough memory for the entire mesh to be refined once, so that a user could end up with an entire mesh at nest level initNest + 1 if every panel triggers the adaptive refinement criteria. Typical settings are AMR = 3 or AMR = 4 for adaptively refined mesh simulations.
Function/Subroutine Documentation
real(kreal) function, public spheremeshmodule::averagelagrangianparametervariation (type(spheremesh), intent(in) self)
Estimates the average edge length of a panel in Lagrangian coordinate space.
Author
Peter Bosler
Parameters
in,out self SphereMesh object
Returns
approximate edge length, $ \sqrt{4\pi R^2/N} $
Definition at line 820 of file SphereMesh2.f90.
Referenced by converttorelativetolerances().
subroutine, public spheremeshmodule::ccwedgesandparticlesaroundpanel (integer(kint), dimension(:), intent(inout) edgeList, integer(kint), dimension(:), intent(inout) vertList, integer(kint), intent(inout) nVerts, type(spheremesh), intent(in) self, integer(kint), intent(in) panelIndex)
Determines the adjacency information of a panel within a SphereMesh.
Author
Peter Bosler
Parameters
in,out edgeList integer array; on output, contains a CCW list of pointers to Edges around panel
in,out vertList integer array; on output, contains a CCW list of particles (vertices) around panel
in,out nVerts integer; on output provides the number of edges (= number of vertices) around panel
in self SphereMesh object
in panelIndex integer; pointer to panel whose adjacency information is needed
Definition at line 395 of file SphereMesh2.f90.
References panelsmodule::getpanelkind().
real(kreal) function, public spheremeshmodule::getrossbynumber (type(spheremesh), intent(in) self)
Computes the Rossby number of the current vorticity distribution.
Author
Peter Bosler
Parameters
in self SphereMesh object
Returns
Rossby Number Ro, double precision real
Definition at line 567 of file SphereMesh2.f90.
Referenced by bvegaussvort(), and rh4wave().
integer(kint) function, public spheremeshmodule::locatepoint (type(spheremesh), intent(in) self, real(kreal), dimension(3), intent(in) xyz)
Locates an arbitrary point on the sphere within a SphereMesh.
Author
Peter Bosler
Parameters
in self SphereMesh object
in xyz double precision real, size(3); Cartesian coordinates of a point on the sphere
Returns
integer pointer to panel that contains xyz
Definition at line 652 of file SphereMesh2.f90.
References planemeshmodule::locatepoint().
real(kreal) function, public spheremeshmodule::maximumcirculation (type(spheremesh), intent(in) self)
Finds the maximum magnitude of circulation about any panel in a mesh.
Author
Peter Bosler
Parameters
in,out self SphereMesh object
Returns
maximum absolute value of circulation over each panel, $ \max_k |\zeta_k|A_k $
Definition at line 711 of file SphereMesh2.f90.
References planemeshmodule::maximumcirculation().
real(kreal) function, public spheremeshmodule::maximumlagrangianparametervariation (type(spheremesh), intent(in) self)
Finds the maximum Lagrangian coordinate variation over each panel in a SphereMesh.
Author
Peter Bosler
Parameters
in,out self SphereMesh object
Returns
maximum Lagrangian coordinate variation all panels
Definition at line 840 of file SphereMesh2.f90.
References planemeshmodule::ccwedgesandparticlesaroundpanel(), planemeshmodule::maximumlagrangianparametervariation(), and spheregeommodule::spheretricenter().
real(kreal) function, public spheremeshmodule::maximumtracermass (type(spheremesh), intent(in) self, integer(kint), intent(in) tracerID)
Finds the maximum amount of tracer mass contained in any panel in a mesh.
Author
Peter Bosler
Parameters
in,out self SphereMesh object
Returns
maximum tracer mass contained in a panel over a SphereMesh, , $ \max_k \phi_k A_k - \min_k \phi_k A_k $
Definition at line 734 of file SphereMesh2.f90.
References planemeshmodule::maximumtracermass().
real(kreal) function, public spheremeshmodule::maximumtracervariation (type(spheremesh), intent(in) self, integer(kint), intent(in) tracerID)
Finds the maximum variation of a passive tracer over a whole SphereMesh.
Author
Peter Bosler
Parameters
in,out self SphereMesh object
in tracerID integer; identification number of tracer whose variation is desired
Returns
maximum tracer variation over the sphere , $ \max_S \phi - \min_S\phi $
Definition at line 757 of file SphereMesh2.f90.
References planemeshmodule::maximumtracervariation().
real(kreal) function, public spheremeshmodule::maximumvorticityvariation (type(spheremesh), intent(in) self)
Finds the maximum variation of a relative vorticiy over a whole SphereMesh.
Author
Peter Bosler
Parameters
in,out self SphereMesh object
Returns
maximum relative vorticity variation over the sphere, $ \max_S \zeta - \min_S\zeta $
Definition at line 789 of file SphereMesh2.f90.
References planemeshmodule::maximumvorticityvariation().
subroutine, public spheremeshmodule::renormalize (type(spheremesh), intent(inout) self)
Resets position vector of all particles in SphereMesh object to satisfy x^2 + y^2 + z^2 = R^2.
Author
Peter Bosler
Parameters
in,out self SphereMesh object
Definition at line 308 of file SphereMesh2.f90.
References panelsmodule::getpanelkind().
subroutine, public spheremeshmodule::resetspherearea (type(spheremesh), intent(inout) self)
Resets area of all panels in SphereMesh.
Author
Peter Bosler
Parameters
in,out self SphereMesh object
Definition at line 365 of file SphereMesh2.f90.
real(kreal) function, public spheremeshmodule::totalabsvort (type(spheremesh), intent(in) self)
Computes the total integral of a absolute vorticity over the sphere using midpoint rule quadrature.
Author
Peter Bosler
Parameters
in self SphereMesh object
in tracerNumber integer, identification number of passive tracer whose integral is to be computed
Returns
double precsion real, $ \int_S \omega \, dA \approx \sum_{k=1}^N \omega_k A_k $
Definition at line 501 of file SphereMesh2.f90.
real(kreal) function, public spheremeshmodule::totalenstrophy (type(spheremesh), intent(in) self)
Computes the total enstrophy over the sphere using midpoint rule quadrature.
Author
Peter Bosler
Parameters
in self SphereMesh object
in tracerNumber integer, identification number of passive tracer whose integral is to be computed
Returns
double precsion real, $ \int_S \zeta^2 \, dA \approx \sum_{k=1}^N \zeta_k^2 A_k $
Definition at line 620 of file SphereMesh2.f90.
Referenced by bvegaussvort(), lambtest(), reversibledipolesmain(), rh4wave(), and twodipolesmain().
real(kreal) function, public spheremeshmodule::totalmass (type(spheremesh), intent(in) self, integer(kint), intent(in) tracerNumber)
Computes the total integral of a tracer over the sphere using midpoint rule quadrature.
Author
Peter Bosler
Parameters
in self SphereMesh object
in tracerNumber integer, identification number of passive tracer whose integral is to be computed
Returns
double precsion real, $ \int_S \phi \, dA \approx \sum_{k=1}^N \phi_k A_k $
Definition at line 470 of file SphereMesh2.f90.
Referenced by bvegaussvort(), gaussianhillsadvection(), gaussianhillsadvectiondirect(), kentcascadeadvection(), movingvorticesadvection(), and planerotateadvection().
real(kreal) function, public spheremeshmodule::totalrelvort (type(spheremesh), intent(in) self)
Computes the total integral of relative vorticity over the sphere using midpoint rule quadrature.
Author
Peter Bosler
Parameters
in self SphereMesh object
in tracerNumber integer, identification number of passive tracer whose integral is to be computed
Returns
double precsion real, $ \int_S \zeta \, dA \approx \sum_{k=1}^N \zeta_k A_k $
Definition at line 588 of file SphereMesh2.f90.