Advection
Provides data structures and methods for RK4 timestepping meshes in advection problems on a sphere.
Functions/Subroutines
subroutine, public advectionmodule::advectionrk4timestep (self, aMesh, dt, t, procRank, nProcs, velocityFunction)
Advances a spherical mesh advection problem one time step using 4th order Runge-Kutta.
subroutine, public advectionmodule::zerork4 (self)
Sets arrays used by Runge-Kutta to zero to prevent contamination of current timestep from previous data.
subroutine, public advectionmodule::setalpha (newAlpha)
Sets the angle of inclination (relative to the z-axis) for solid body rotation.
real(kreal) function,
*
dimension(3), public advectionmodule::lauritzenetalnondivergentwind (xyz, t)
Outputs velocity at postion xyz and time t corresponding to the non-divergent test cases found in .
real(kreal) function,
*
dimension(3), public advectionmodule::lauritzenetaldivergentwind (xyz, t)
Outputs velocity at postion xyz and time t corresponding to the divergent test cases found in .
real(kreal) function,
*
dimension(3), public advectionmodule::testcase1velocity (xyz, t)
Outputs velocity at postion xyz and time t corresponding to test case 1.
real(kreal) function,
*
dimension(3), public advectionmodule::movingvorticesvelocity (xyz, t)
Outputs velocity at postion xyz and time t corresponding to moving vortices test case.
real(kreal) function,
*
dimension(3), public advectionmodule::kentcascadevelocity (xyz, t)
Outputs velocity at postion xyz and time t corresponding to tracer cascade test case.
Detailed Description
Provides data structures and methods for RK4 timestepping meshes in advection problems on a sphere.
Author
Peter Bosler, Department of Mathematics, University of Michigan
Function/Subroutine Documentation
subroutine, public advectionmodule::advectionrk4timestep (type(advrk4data), intent(inout) self, type(spheremesh), intent(inout) aMesh, real(kreal), intent(in) dt, real(kreal), intent(in) t, integer(kint), intent(in) procRank, integer(kint), intent(in) nProcs, procedure(advectionvelocity) velocityFunction)
Advances a spherical mesh advection problem one time step using 4th order Runge-Kutta.
Author
Peter Bosler.
Parameters
in dt double precision real, timestep size
in t double precision real, current simulation time
in procRank integer, MPI process rank
in nProcs integer, number of MPI processes
in velocityFunction,interface to advection velocity functions
in,out self AdvectionRK4 object
in,out aMesh SphereMesh object
Definition at line 381 of file Advection2.f90.
References panelsmodule::scatterpanels(), and advectionmodule::zerork4().
Referenced by gaussianhillsadvection(), gaussianhillsadvectiondirect(), kentcascadeadvection(), movingvorticesadvection(), and testcase1().
real(kreal) function, dimension(3), public advectionmodule::kentcascadevelocity (real(kreal), dimension(3), intent(in) xyz, real(kreal), intent(in) t)
Outputs velocity at postion xyz and time t corresponding to tracer cascade test case.
Author
Peter Bosler
Parameters
in xyz double precision real, size(3); position vector in Cartesian coordinates of a point on the sphere
in t double precision real; current value of simulation time variable
Returns
velocity vector double precision real, size(3); tangent to sphere
Definition at line 860 of file Advection2.f90.
Referenced by kentcascadeadvection().
real(kreal) function, dimension(3), public advectionmodule::lauritzenetaldivergentwind (real(kreal), dimension(3), intent(in) xyz, real(kreal), intent(in) t)
Outputs velocity at postion xyz and time t corresponding to the divergent test cases found in .
Author
Peter Bosler
Parameters
in xyz double precision real, size(3); position vector in Cartesian coordinates of a point on the sphere
in t double precision real; current value of simulation time variable
Returns
velocity vector double precision real, size(3); tangent to sphere
Definition at line 761 of file Advection2.f90.
real(kreal) function, dimension(3), public advectionmodule::lauritzenetalnondivergentwind (real(kreal), dimension(3), intent(in) xyz, real(kreal), intent(in) t)
Outputs velocity at postion xyz and time t corresponding to the non-divergent test cases found in .
Author
Peter Bosler
Parameters
in xyz double precision real, size(3); position vector in Cartesian coordinates of a point on the sphere
in t double precision real; current value of simulation time variable
Returns
velocity vector double precision real, size(3); tangent to sphere
Definition at line 727 of file Advection2.f90.
Referenced by gaussianhillsadvection(), and gaussianhillsadvectiondirect().
real(kreal) function, dimension(3), public advectionmodule::movingvorticesvelocity (real(kreal), dimension(3), intent(in) xyz, real(kreal), intent(in) t)
Outputs velocity at postion xyz and time t corresponding to moving vortices test case.
Author
Peter Bosler
Parameters
in xyz double precision real, size(3); position vector in Cartesian coordinates of a point on the sphere
in t double precision real; current value of simulation time variable
Returns
velocity vector double precision real, size(3); tangent to sphere
Definition at line 820 of file Advection2.f90.
References spheregeommodule::atan4().
Referenced by movingvorticesadvection().
subroutine, public advectionmodule::setalpha (real(kreal), intent(in) newAlpha)
Sets the angle of inclination (relative to the z-axis) for solid body rotation.
Author
Peter Bosler
Parameters
in newAlpha double precision real
Definition at line 650 of file Advection2.f90.
real(kreal) function, dimension(3), public advectionmodule::testcase1velocity (real(kreal), dimension(3), intent(in) xyz, real(kreal), intent(in) t)
Outputs velocity at postion xyz and time t corresponding to test case 1.
Author
Peter Bosler
Parameters
in xyz double precision real, size(3); position vector in Cartesian coordinates of a point on the sphere
in t double precision real; current value of simulation time variable
Returns
velocity vector double precision real, size(3); tangent to sphere
Definition at line 794 of file Advection2.f90.
Referenced by cubedspheretest(), and testcase1().
subroutine, public advectionmodule::zerork4 (type(advrk4data), intent(inout) self)
Sets arrays used by Runge-Kutta to zero to prevent contamination of current timestep from previous data.
Author
Peter Bosler
Parameters
in self AdvectionRK4 object
Definition at line 589 of file Advection2.f90.
Referenced by advectionmodule::advectionrk4timestep(), bvedirectsummodule::bverk4timestep(), planedirectsummodule::rk4timestepincompressibleadvection(), planedirectsummodule::rk4timestepnorotation(), and swedirectsummodule::swerk4timestep().