spheregeommodule::longitude Interface Reference
Public Member Functions
real(kreal) function longitudevector (xyz)
real(kreal) function longitudecomponents (x, y, z)
real(kreal) function longitudecomponents2 (x, y)
Detailed Description
Definition at line 45 of file SphereGeom3.f90.
Member Function/Subroutine Documentation
real(kreal) function spheregeommodule::longitude::longitudecomponents (real(kreal), intent(in) x, real(kreal), intent(in) y, real(kreal), intent(in) z)
Definition at line 271 of file SphereGeom3.f90.
Referenced by spheregeommodule::longitudecomponents().
real(kreal) function spheregeommodule::longitude::longitudecomponents2 (real(kreal), intent(in) x, real(kreal), intent(in) y)
Definition at line 278 of file SphereGeom3.f90.
Referenced by spheregeommodule::longitudecomponents2().
real(kreal) function spheregeommodule::longitude::longitudevector (real(kreal), dimension(3), intent(in) xyz)
Definition at line 263 of file SphereGeom3.f90.
Referenced by spheregeommodule::longitudevector().
The documentation for this interface was generated from the following file:
SphereGeom3.f90