spheregeommodule::spherearclength Interface Reference
Public Member Functions
real(kreal) function spherearclengthvector (xyzA, xyzB)
real(kreal) function spherearclengthcomponents (xA, yA, zA, xB, yB, zB)
Detailed Description
Definition at line 35 of file SphereGeom3.f90.
Member Function/Subroutine Documentation
real(kreal) function spheregeommodule::spherearclength::spherearclengthcomponents (real(kreal), intent(in) xA, real(kreal), intent(in) yA, real(kreal), intent(in) zA, real(kreal), intent(in) xB, real(kreal), intent(in) yB, real(kreal), intent(in) zB)
Definition at line 126 of file SphereGeom3.f90.
Referenced by spheregeommodule::spherearclengthcomponents(), and spheregeommodule::spheretriareacomponents().
real(kreal) function spheregeommodule::spherearclength::spherearclengthvector (real(kreal), dimension(3), intent(in) xyzA, real(kreal), dimension(3), intent(in) xyzB)
Definition at line 106 of file SphereGeom3.f90.
Referenced by spheregeommodule::spherearclengthvector().
The documentation for this interface was generated from the following file:
SphereGeom3.f90