LambDipole.f90 File Reference
Functions/Subroutines
program lambtest
subroutine readnamelistfile (rank)
subroutine converttorelativetolerances (aMesh, maxCircTol, vortVarTol, lagVarTol)
subroutine storelagrangianxcoordinateintracer (aMesh, tracerID)
Function/Subroutine Documentation
subroutine lambtest::converttorelativetolerances (type(planemesh), intent(in) aMesh, real(kreal), intent(inout) maxCircTol, real(kreal), intent(inout) vortVarTol, real(kreal), intent(inout) lagVarTol)
Definition at line 328 of file LambDipole.f90.
References planemeshmodule::maximumcirculation(), planemeshmodule::maximumlagrangianparametervariation(), and planemeshmodule::maximumvorticityvariation().
program lambtest ()
Definition at line 1 of file LambDipole.f90.
References converttorelativetolerances(), planemeshmodule::gettotalcirculation(), planemeshmodule::gettotalenstrophy(), planemeshmodule::gettotalke(), planemeshmodule::initializerectangle(), refineremeshmodule::initialrefinement(), planevorticitymodule::initlambdipole(), planetracermodule::nulltracer(), planeoutputmodule::outputforvtk(), readnamelistfile(), planedirectsummodule::rk4timestepnorotation(), planevorticitymodule::setlambdipoleonmesh(), storelagrangianxcoordinateintracer(), planemeshmodule::totalarea(), spheremeshmodule::totalenstrophy(), and planeoutputmodule::updatefilename().
subroutine lambtest::readnamelistfile (integer(kint), intent(in) rank)
Definition at line 271 of file LambDipole.f90.
subroutine lambtest::storelagrangianxcoordinateintracer (type(planemesh), intent(inout) aMesh, integer(kint), intent(in) tracerID)
Definition at line 336 of file LambDipole.f90.
Referenced by lambtest(), reversibledipolesmain(), and twodipolesmain().