PlaneRotationalAdvection.f90 File Reference
Functions/Subroutines
program planerotateadvection
subroutine convertfromrelativetolerances (aMesh, maxMassTol, tracerVarTol, lagVarTol)
subroutine readnamelistfile (rank)
subroutine initlogger (aLog, rank)
Function/Subroutine Documentation
subroutine planerotateadvection::convertfromrelativetolerances (type(planemesh), intent(in) aMesh, real(kreal), intent(inout) maxMassTol, real(kreal), intent(inout) tracerVarTol, real(kreal), intent(inout) lagVarTol)
Definition at line 229 of file PlaneRotationalAdvection.f90.
subroutine planerotateadvection::initlogger (type(logger), intent(inout) aLog, integer(kint), intent(in) rank)
Definition at line 293 of file PlaneRotationalAdvection.f90.
program planerotateadvection ()
Definition at line 1 of file PlaneRotationalAdvection.f90.
References planemeshmodule::gettotalmass(), planemeshmodule::initializerectangle(), refineremeshmodule::initialrefinement(), initlogger(), planetracermodule::initthreetracers(), planedirectsummodule::leveque93(), bvesetupmodule::nullvorticity(), planeoutputmodule::outputforvtk(), readnamelistfile(), planedirectsummodule::rk4timestepincompressibleadvection(), planetracermodule::setthreetracersonmesh(), planemeshmodule::totalarea(), spheremeshmodule::totalmass(), and planeoutputmodule::updatefilename().
subroutine planerotateadvection::readnamelistfile (integer(kint), intent(in) rank)
Definition at line 234 of file PlaneRotationalAdvection.f90.