planeTester.f90 File Reference
Functions/Subroutines
program planeunittest
subroutine readnamelistfile (rank)
subroutine converttorelativetolerances (aMesh, maxCircTol, vortVarTol, lagVarTol)
Function/Subroutine Documentation
subroutine planeunittest::converttorelativetolerances (type(planemesh), intent(in) aMesh, real(kreal), intent(inout) maxCircTol, real(kreal), intent(inout) vortVarTol, real(kreal), intent(inout) lagVarTol)
Definition at line 234 of file planeTester.f90.
References planemeshmodule::maximumcirculation(), planemeshmodule::maximumlagrangianparametervariation(), and planemeshmodule::maximumvorticityvariation().
program planeunittest ()
Definition at line 1 of file planeTester.f90.
References converttorelativetolerances(), planemeshmodule::initializerectangle(), refineremeshmodule::initialrefinement(), planevorticitymodule::initrankinevortex(), planetracermodule::nulltracer(), planeoutputmodule::outputforvtk(), readnamelistfile(), planedirectsummodule::rk4timestepnorotation(), planevorticitymodule::setrankinevortexonmesh(), planemeshmodule::totalarea(), and planeoutputmodule::updatefilename().
subroutine planeunittest::readnamelistfile (integer(kint), intent(in) rank)
Definition at line 191 of file planeTester.f90.