PlaneVorticity.f90 File Reference
defines vorticity distributions for incompressible flow in 2d Cartesian geometry
Data Types
module planevorticitymodule
Functions/Subroutines
real *8 function bessj0 (X)
real *8 function bessj1 (X)
Detailed Description
defines vorticity distributions for incompressible flow in 2d Cartesian geometry
Definition in file PlaneVorticity.f90.
Function/Subroutine Documentation
real *8 function bessj0 (real *8 X)
Definition at line 384 of file PlaneVorticity.f90.
Referenced by planevorticitymodule::lambdipole(), and planevorticitymodule::twodipoles().
real *8 function bessj1 (real *8 X)
Definition at line 425 of file PlaneVorticity.f90.
Referenced by planevorticitymodule::lambdipole(), and planevorticitymodule::twodipoles().