ReversibleDipoles.f90 File Reference
Functions/Subroutines
program reversibledipolesmain
subroutine reversevorticity (aMesh, aRef)
subroutine readnamelistfile (rank)
subroutine converttorelativetolerances (aMesh, maxCircTol, vortVarTol, lagVarTol)
subroutine storelagrangianxcoordinateintracer (aMesh, tracerID)
subroutine initlogger (aLog, rank)
Function/Subroutine Documentation
subroutine reversibledipolesmain::converttorelativetolerances (type(planemesh), intent(in) aMesh, real(kreal), intent(inout) maxCircTol, real(kreal), intent(inout) vortVarTol, real(kreal), intent(inout) lagVarTol)
Definition at line 412 of file ReversibleDipoles.f90.
References planemeshmodule::maximumcirculation(), planemeshmodule::maximumlagrangianparametervariation(), and planemeshmodule::maximumvorticityvariation().
subroutine reversibledipolesmain::initlogger (type(logger), intent(inout) aLog, integer(kint), intent(in) rank)
Definition at line 442 of file ReversibleDipoles.f90.
subroutine reversibledipolesmain::readnamelistfile (integer(kint), intent(in) rank)
Definition at line 335 of file ReversibleDipoles.f90.
subroutine reversibledipolesmain::reversevorticity (type(planemesh), intent(inout) aMesh, type(bivarsetup), intent(inout) aRef)
Definition at line 305 of file ReversibleDipoles.f90.
Referenced by reversibledipolesmain().
program reversibledipolesmain ()
Definition at line 1 of file ReversibleDipoles.f90.
References converttorelativetolerances(), planemeshmodule::gettotalcirculation(), planemeshmodule::gettotalenstrophy(), planemeshmodule::gettotalke(), planetracermodule::initdipoleidtracer(), planemeshmodule::initializerectangle(), refineremeshmodule::initialrefinement(), initlogger(), planevorticitymodule::inittwodipoles(), planeoutputmodule::outputforvtk(), readnamelistfile(), reversevorticity(), planedirectsummodule::rk4timestepnorotation(), planetracermodule::setdipoleidtraceronmesh(), planevorticitymodule::settwodipolesonmesh(), storelagrangianxcoordinateintracer(), planemeshmodule::totalarea(), spheremeshmodule::totalenstrophy(), and planeoutputmodule::updatefilename().
subroutine reversibledipolesmain::storelagrangianxcoordinateintracer (type(planemesh), intent(inout) aMesh, integer(kint), intent(in) tracerID)
Definition at line 422 of file ReversibleDipoles.f90.