ssrfpack.f File Reference
Functions/Subroutines
subroutine aplyr (X, Y, Z, CX, SX, CY, SY, XP, YP, ZP)
subroutine aplyrt (G1P, G2P, CX, SX, CY, SY, G)
subroutine arcint (P, P1, P2, F1, F2, G1, G2, SIGMA, F, G, GN)
real(kind=8) function arclen (P, Q)
subroutine constr (XK, YK, ZK, CX, SX, CY, SY)
real(kind=8) function fval (B1, B2, B3, V1, V2, V3, F1, F2, F3, G1, G2, G3, SIG1, SIG2, SIG3)
subroutine getsig (N, X, Y, Z, H, LIST, LPTR, LEND, GRAD, TOL, SIGMA, DSMAX, IER)
subroutine givens (A, B, C, S)
subroutine gradg (N, X, Y, Z, F, LIST, LPTR, LEND, IFLGS, SIGMA, NIT, DGMAX, GRAD, IER)
subroutine gradl (N, K, X, Y, Z, W, LIST, LPTR, LEND, G, IER)
subroutine grcoef (SIGMA, D, SD)
real(kind=8) function hval (B, H1, H2, HP1, HP2, SIGMA)
subroutine intrc0 (N, PLAT, PLON, X, Y, Z, W, LIST, LPTR, LEND, IST, PW, IER)
subroutine intrc1 (N, PLAT, PLON, X, Y, Z, F, LIST, LPTR, LEND, IFLGS, SIGMA, IFLGG, GRAD, IST, FP, IER)
subroutine rotate (N, C, S, X, Y)
subroutine setup (XI, YI, WI, WK, S1, S2, WT, ROW)
subroutine sgprnt (N, LUNIT, LIST, LPTR, LEND, SIGMA)
real(kind=8) function sig0 (N1, N2, N, X, Y, Z, H, LIST, LPTR, LEND, GRAD, IFLGB, HBND, TOL, IFLGS, SIGMA, IER)
real(kind=8) function sig1 (N1, N2, N, X, Y, Z, H, LIST, LPTR, LEND, GRAD, IFLGB, HPBND, TOL, IFLGS, SIGMA, IER)
real(kind=8) function sig2 (N1, N2, N, X, Y, Z, H, LIST, LPTR, LEND, GRAD, TOL, IFLGS, SIGMA, IER)
subroutine smsgs (N, X, Y, Z, U, LIST, LPTR, LEND, IFLGS, SIGMA, W, P, NIT, DFMAX, F, GRAD, IER)
subroutine smsurf (N, X, Y, Z, U, LIST, LPTR, LEND, IFLGS, SIGMA, W, SM, SMTOL, GSTOL, LPRNT, F, GRAD, IER)
subroutine snhcsh (X, SINHM, COSHM, COSHMM)
subroutine unif (N, X, Y, Z, F, LIST, LPTR, LEND, IFLGS, SIGMA, NROW, NI, NJ, PLAT, PLON, IFLGG, GRAD, FF, IER)
Function/Subroutine Documentation
subroutine aplyr (real(kind=8) X, real(kind=8) Y, real(kind=8) Z, real(kind=8) CX, real(kind=8) SX, real(kind=8) CY, real(kind=8) SY, real(kind=8) XP, real(kind=8) YP, real(kind=8) ZP)
Definition at line 1 of file ssrfpack.f.
Referenced by gradl().
subroutine aplyrt (real(kind=8) G1P, real(kind=8) G2P, real(kind=8) CX, real(kind=8) SX, real(kind=8) CY, real(kind=8) SY, real(kind=8), dimension(3) G)
Definition at line 71 of file ssrfpack.f.
Referenced by gradg(), gradl(), and smsgs().
subroutine arcint (real(kind=8), dimension(3) P, real(kind=8), dimension(3) P1, real(kind=8), dimension(3) P2, real(kind=8) F1, real(kind=8) F2, real(kind=8), dimension(3) G1, real(kind=8), dimension(3) G2, real(kind=8) SIGMA, real(kind=8) F, real(kind=8), dimension(3) G, real(kind=8) GN)
Definition at line 121 of file ssrfpack.f.
References arclen(), and snhcsh().
Referenced by fval(), and intrc1().
real(kind=8) function arclen (real(kind=8), dimension(3) P, real(kind=8), dimension(3) Q)
Definition at line 333 of file ssrfpack.f.
Referenced by arcint(), getsig(), intrc1(), sig0(), sig1(), and sig2().
subroutine constr (real(kind=8) XK, real(kind=8) YK, real(kind=8) ZK, real(kind=8) CX, real(kind=8) SX, real(kind=8) CY, real(kind=8) SY)
Definition at line 394 of file ssrfpack.f.
Referenced by gradg(), gradl(), and smsgs().
real(kind=8) function fval (real(kind=8) B1, real(kind=8) B2, real(kind=8) B3, real(kind=8), dimension(3) V1, real(kind=8), dimension(3) V2, real(kind=8), dimension(3) V3, real(kind=8) F1, real(kind=8) F2, real(kind=8) F3, real(kind=8), dimension(3) G1, real(kind=8), dimension(3) G2, real(kind=8), dimension(3) G3, real(kind=8) SIG1, real(kind=8) SIG2, real(kind=8) SIG3)
Definition at line 447 of file ssrfpack.f.
References arcint(), hval(), sig1(), and sig2().
Referenced by intrc1().
subroutine getsig (integer N, real(kind=8), dimension(n) X, real(kind=8), dimension(n) Y, real(kind=8), dimension(n) Z, real(kind=8), dimension(n) H, integer, dimension(*) LIST, integer, dimension(*) LPTR, integer, dimension(n) LEND, real(kind=8), dimension(3,n) GRAD, real(kind=8) TOL, real(kind=8), dimension(*) SIGMA, real(kind=8) DSMAX, integer IER)
Definition at line 664 of file ssrfpack.f.
References arclen(), lstptr(), snhcsh(), and store().
Referenced by ssrfpackinterfacemodule::setsourceabsvort(), ssrfpackinterfacemodule::setsourcekineticenergy(), ssrfpackinterfacemodule::setsourcelagrangianparameter(), ssrfpackinterfacemodule::setsourcerelvort(), and ssrfpackinterfacemodule::setsourcetracer().
subroutine givens (real(kind=8) A, real(kind=8) B, real(kind=8) C, real(kind=8) S)
Definition at line 1121 of file ssrfpack.f.
Referenced by gradl().
subroutine gradg (integer N, real(kind=8), dimension(n) X, real(kind=8), dimension(n) Y, real(kind=8), dimension(n) Z, real(kind=8), dimension(n) F, integer, dimension(*) LIST, integer, dimension(*) LPTR, integer, dimension(n) LEND, integer IFLGS, real(kind=8), dimension(*) SIGMA, integer NIT, real(kind=8) DGMAX, real(kind=8), dimension(3,n) GRAD, integer IER)
Definition at line 1223 of file ssrfpack.f.
References aplyrt(), constr(), and grcoef().
subroutine gradl (integer N, integer K, real(kind=8), dimension(n) X, real(kind=8), dimension(n) Y, real(kind=8), dimension(n) Z, real(kind=8), dimension(n) W, integer, dimension(*) LIST, integer, dimension(*) LPTR, integer, dimension(n) LEND, real(kind=8), dimension(3) G, integer IER)
Definition at line 1558 of file ssrfpack.f.
References aplyr(), aplyrt(), constr(), getnp(), givens(), rotate(), and setup().
Referenced by intrc1(), ssrfpackinterfacemodule::setsourceabsvort(), ssrfpackinterfacemodule::setsourcekineticenergy(), ssrfpackinterfacemodule::setsourcelagrangianparameter(), ssrfpackinterfacemodule::setsourcerelvort(), ssrfpackinterfacemodule::setsourcetracer(), swedirectsummodule::setvelocitysmoothingparameter(), ssrfpackapproximations(), and unif().
subroutine grcoef (real(kind=8) SIGMA, real(kind=8) D, real(kind=8) SD)
Definition at line 1881 of file ssrfpack.f.
References snhcsh().
Referenced by gradg(), and smsgs().
real(kind=8) function hval (real(kind=8) B, real(kind=8) H1, real(kind=8) H2, real(kind=8) HP1, real(kind=8) HP2, real(kind=8) SIGMA)
Definition at line 1955 of file ssrfpack.f.
References snhcsh().
Referenced by fval().
subroutine intrc0 (integer N, real(kind=8) PLAT, real(kind=8) PLON, real(kind=8), dimension(n) X, real(kind=8), dimension(n) Y, real(kind=8), dimension(n) Z, real(kind=8), dimension(n) W, integer, dimension(*) LIST, integer, dimension(*) LPTR, integer, dimension(n) LEND, integer IST, real(kind=8) PW, integer IER)
Definition at line 2057 of file ssrfpack.f.
References trfind().
subroutine intrc1 (integer N, real(kind=8) PLAT, real(kind=8) PLON, real(kind=8), dimension(n) X, real(kind=8), dimension(n) Y, real(kind=8), dimension(n) Z, real(kind=8), dimension(n) F, integer, dimension(*) LIST, integer, dimension(*) LPTR, integer, dimension(n) LEND, integer IFLGS, real(kind=8), dimension(*) SIGMA, integer IFLGG, real(kind=8), dimension(3,n) GRAD, integer IST, real(kind=8) FP, integer IER)
Definition at line 2282 of file ssrfpack.f.
References arcint(), arclen(), fval(), gradl(), lstptr(), and trfind().
Referenced by ssrfpackinterfacemodule::interpolatescalar(), ssrfpackinterfacemodule::interpolatetracer(), ssrfpackinterfacemodule::interpolatevector(), and unif().
subroutine rotate (integer N, real(kind=8) C, real(kind=8) S, real(kind=8), dimension(n) X, real(kind=8), dimension(n) Y)
Definition at line 2686 of file ssrfpack.f.
Referenced by gradl().
subroutine setup (real(kind=8) XI, real(kind=8) YI, real(kind=8) WI, real(kind=8) WK, real(kind=8) S1, real(kind=8) S2, real(kind=8) WT, real(kind=8), dimension(6) ROW)
Definition at line 2741 of file ssrfpack.f.
Referenced by gradl().
subroutine sgprnt (integer N, integer LUNIT, integer, dimension(*) LIST, integer, dimension(*) LPTR, integer, dimension(n) LEND, real(kind=8), dimension(*) SIGMA)
Definition at line 2803 of file ssrfpack.f.
References lstptr().
real(kind=8) function sig0 (integer N1, integer N2, integer N, real(kind=8), dimension(n) X, real(kind=8), dimension(n) Y, real(kind=8), dimension(n) Z, real(kind=8), dimension(n) H, integer, dimension(*) LIST, integer, dimension(*) LPTR, integer, dimension(n) LEND, real(kind=8), dimension(3,n) GRAD, integer IFLGB, real(kind=8) HBND, real(kind=8) TOL, integer IFLGS, real(kind=8), dimension(*) SIGMA, integer IER)
Definition at line 2963 of file ssrfpack.f.
References arclen(), snhcsh(), and store().
real(kind=8) function sig1 (integer N1, integer N2, integer N, real(kind=8), dimension(n) X, real(kind=8), dimension(n) Y, real(kind=8), dimension(n) Z, real(kind=8), dimension(n) H, integer, dimension(*) LIST, integer, dimension(*) LPTR, integer, dimension(n) LEND, real(kind=8), dimension(3,n) GRAD, integer IFLGB, real(kind=8) HPBND, real(kind=8) TOL, integer IFLGS, real(kind=8), dimension(*) SIGMA, integer IER)
Definition at line 3398 of file ssrfpack.f.
References arclen(), snhcsh(), and store().
Referenced by fval().
real(kind=8) function sig2 (integer N1, integer N2, integer N, real(kind=8), dimension(n) X, real(kind=8), dimension(n) Y, real(kind=8), dimension(n) Z, real(kind=8), dimension(n) H, integer, dimension(*) LIST, integer, dimension(*) LPTR, integer, dimension(n) LEND, real(kind=8), dimension(3,n) GRAD, real(kind=8) TOL, integer IFLGS, real(kind=8), dimension(*) SIGMA, integer IER)
Definition at line 3795 of file ssrfpack.f.
References arclen(), snhcsh(), and store().
Referenced by fval().
subroutine smsgs (integer N, real(kind=8), dimension(n) X, real(kind=8), dimension(n) Y, real(kind=8), dimension(n) Z, real(kind=8), dimension(n) U, integer, dimension(*) LIST, integer, dimension(*) LPTR, integer, dimension(n) LEND, integer IFLGS, real(kind=8), dimension(*) SIGMA, real(kind=8), dimension(n) W, real(kind=8) P, integer NIT, real(kind=8) DFMAX, real(kind=8), dimension(n) F, real(kind=8), dimension(3,n) GRAD, integer IER)
Definition at line 4076 of file ssrfpack.f.
References aplyrt(), constr(), and grcoef().
Referenced by smsurf().
subroutine smsurf (integer N, real(kind=8), dimension(n) X, real(kind=8), dimension(n) Y, real(kind=8), dimension(n) Z, real(kind=8), dimension(n) U, integer, dimension(*) LIST, integer, dimension(*) LPTR, integer, dimension(n) LEND, integer IFLGS, real(kind=8), dimension(*) SIGMA, real(kind=8), dimension(n) W, real(kind=8) SM, real(kind=8) SMTOL, real(kind=8) GSTOL, integer LPRNT, real(kind=8), dimension(n) F, real(kind=8), dimension(3,n) GRAD, integer IER)
Definition at line 4341 of file ssrfpack.f.
References smsgs().
subroutine snhcsh (real(kind=8) X, real(kind=8) SINHM, real(kind=8) COSHM, real(kind=8) COSHMM)
Definition at line 4658 of file ssrfpack.f.
Referenced by arcint(), getsig(), grcoef(), hval(), sig0(), sig1(), and sig2().
subroutine unif (integer N, real(kind=8), dimension(n) X, real(kind=8), dimension(n) Y, real(kind=8), dimension(n) Z, real(kind=8), dimension(n) F, integer, dimension(*) LIST, integer, dimension(*) LPTR, integer, dimension(n) LEND, integer IFLGS, real(kind=8), dimension(*) SIGMA, integer NROW, integer NI, integer NJ, real(kind=8), dimension(ni) PLAT, real(kind=8), dimension(nj) PLON, integer IFLGG, real(kind=8), dimension(3,n) GRAD, real(kind=8), dimension(nrow,nj) FF, integer IER)
Definition at line 4731 of file ssrfpack.f.
References gradl(), and intrc1().