stripack.f File Reference
Functions/Subroutines
subroutine addnod (NST, K, X, Y, Z, LIST, LPTR, LEND, LNEW, IER)
real(kind=8) function areas (V1, V2, V3)
subroutine bdyadd (KK, I1, I2, LIST, LPTR, LEND, LNEW)
subroutine bnodes (N, LIST, LPTR, LEND, NODES, NB, NA, NT)
subroutine circum (V1, V2, V3, C, IER)
subroutine covsph (KK, N0, LIST, LPTR, LEND, LNEW)
subroutine crlist (N, NCOL, X, Y, Z, LIST, LEND, LPTR, LNEW, LTRI, LISTC, NB, XC, YC, ZC, RC, IER)
subroutine delarc (N, IO1, IO2, LIST, LPTR, LEND, LNEW, IER)
subroutine delnb (N0, NB, N, LIST, LPTR, LEND, LNEW, LPH)
subroutine delnod (K, N, X, Y, Z, LIST, LPTR, LEND, LNEW, LWK, IWK, IER)
subroutine edge (IN1, IN2, X, Y, Z, LWK, IWK, LIST, LPTR, LEND, IER)
subroutine getnp (X, Y, Z, LIST, LPTR, LEND, L, NPTS, DF, IER)
subroutine insert (K, LP, LIST, LPTR, LNEW)
logical function inside (P, LV, XV, YV, ZV, NV, LISTV, IER)
subroutine intadd (KK, I1, I2, I3, LIST, LPTR, LEND, LNEW)
subroutine intrsc (P1, P2, CN, P, IER)
integer function jrand (N, IX, IY, IZ)
logical function left (X1, Y1, Z1, X2, Y2, Z2, X0, Y0, Z0)
integer function lstptr (LPL, NB, LIST, LPTR)
integer function nbcnt (LPL, LPTR)
integer function nearnd (P, IST, N, X, Y, Z, LIST, LPTR, LEND, AL)
subroutine optim (X, Y, Z, NA, LIST, LPTR, LEND, NIT, IWK, IER)
subroutine scoord (PX, PY, PZ, PLAT, PLON, PNRM)
real(kind=8) function store (X)
subroutine swap (IN1, IN2, IO1, IO2, LIST, LPTR, LEND, LP21)
logical function swptst (N1, N2, N3, N4, X, Y, Z)
subroutine trans (N, RLAT, RLON, X, Y, Z)
subroutine trfind (NST, P, N, X, Y, Z, LIST, LPTR, LEND, B1, B2, B3, I1, I2, I3)
subroutine trlist (N, LIST, LPTR, LEND, NROW, NT, LTRI, IER)
subroutine trlprt (N, X, Y, Z, IFLAG, NROW, NT, LTRI, LOUT)
subroutine trmesh (N, X, Y, Z, LIST, LPTR, LEND, LNEW, NEAR, NEXT, DIST, IER)
subroutine trplot (LUN, PLTSIZ, ELAT, ELON, A, N, X, Y, Z, LIST, LPTR, LEND, TITLE, NUMBR, IER)
subroutine trprnt (N, X, Y, Z, IFLAG, LIST, LPTR, LEND, LOUT)
subroutine vrplot (LUN, PLTSIZ, ELAT, ELON, A, N, X, Y, Z, NT, LISTC, LPTR, LEND, XC, YC, ZC, TITLE, NUMBR, IER)
Function/Subroutine Documentation
subroutine addnod (integer NST, integer K, real(kind=8), dimension(k) X, real(kind=8), dimension(k) Y, real(kind=8), dimension(k) Z, integer, dimension(*) LIST, integer, dimension(*) LPTR, integer, dimension(k) LEND, integer LNEW, integer IER)
Definition at line 1 of file stripack.f.
References bdyadd(), covsph(), intadd(), lstptr(), swap(), swptst(), and trfind().
Referenced by trmesh().
real(kind=8) function areas (real(kind=8), dimension(3) V1, real(kind=8), dimension(3) V2, real(kind=8), dimension(3) V3)
Definition at line 216 of file stripack.f.
subroutine bdyadd (integer KK, integer I1, integer I2, integer, dimension(*) LIST, integer, dimension(*) LPTR, integer, dimension(*) LEND, integer LNEW)
Definition at line 345 of file stripack.f.
References insert().
Referenced by addnod().
subroutine bnodes (integer N, integer, dimension(*) LIST, integer, dimension(*) LPTR, integer, dimension(n) LEND, integer, dimension(*) NODES, integer NB, integer NA, integer NT)
Definition at line 460 of file stripack.f.
subroutine circum (real(kind=8), dimension(3) V1, real(kind=8), dimension(3) V2, real(kind=8), dimension(3) V3, real(kind=8), dimension(3) C, integer IER)
Definition at line 562 of file stripack.f.
Referenced by crlist().
subroutine covsph (integer KK, integer N0, integer, dimension(*) LIST, integer, dimension(*) LPTR, integer, dimension(*) LEND, integer LNEW)
Definition at line 653 of file stripack.f.
References insert().
Referenced by addnod().
subroutine crlist (integer N, integer NCOL, real(kind=8), dimension(n) X, real(kind=8), dimension(n) Y, real(kind=8), dimension(n) Z, integer, dimension(*) LIST, integer, dimension(n) LEND, integer, dimension(*) LPTR, integer LNEW, integer, dimension(6,ncol) LTRI, integer, dimension(*) LISTC, integer NB, real(kind=8), dimension(*) XC, real(kind=8), dimension(*) YC, real(kind=8), dimension(*) ZC, real(kind=8), dimension(*) RC, integer IER)
Definition at line 740 of file stripack.f.
References circum(), lstptr(), and swptst().
subroutine delarc (integer N, integer IO1, integer IO2, integer, dimension(*) LIST, integer, dimension(*) LPTR, integer, dimension(n) LEND, integer LNEW, integer IER)
Definition at line 1277 of file stripack.f.
References delnb(), and lstptr().
subroutine delnb (integer N0, integer NB, integer N, integer, dimension(*) LIST, integer, dimension(*) LPTR, integer, dimension(n) LEND, integer LNEW, integer LPH)
Definition at line 1420 of file stripack.f.
Referenced by delarc(), and delnod().
subroutine delnod (integer K, integer N, real(kind=8), dimension(*) X, real(kind=8), dimension(*) Y, real(kind=8), dimension(*) Z, integer, dimension(*) LIST, integer, dimension(*) LPTR, integer, dimension(*) LEND, integer LNEW, integer LWK, integer, dimension(2,*) IWK, integer IER)
Definition at line 1569 of file stripack.f.
References delnb(), left(), lstptr(), nbcnt(), optim(), and swap().
subroutine edge (integer IN1, integer IN2, real(kind=8), dimension(*) X, real(kind=8), dimension(*) Y, real(kind=8), dimension(*) Z, integer LWK, integer, dimension(2,*) IWK, integer, dimension(*) LIST, integer, dimension(*) LPTR, integer, dimension(*) LEND, integer IER)
Definition at line 2012 of file stripack.f.
References left(), optim(), and swap().
subroutine getnp (real(kind=8), dimension(*) X, real(kind=8), dimension(*) Y, real(kind=8), dimension(*) Z, integer, dimension(*) LIST, integer, dimension(*) LPTR, integer, dimension(*) LEND, integer L, integer, dimension(l) NPTS, real(kind=8) DF, integer IER)
Definition at line 2543 of file stripack.f.
Referenced by gradl().
subroutine insert (integer K, integer LP, integer, dimension(*) LIST, integer, dimension(*) LPTR, integer LNEW)
Definition at line 2685 of file stripack.f.
Referenced by bdyadd(), covsph(), and intadd().
logical function inside (real(kind=8), dimension(3) P, integer LV, real(kind=8), dimension(lv) XV, real(kind=8), dimension(lv) YV, real(kind=8), dimension(lv) ZV, integer NV, integer, dimension(nv) LISTV, integer IER)
Definition at line 2736 of file stripack.f.
References intrsc().
subroutine intadd (integer KK, integer I1, integer I2, integer I3, integer, dimension(*) LIST, integer, dimension(*) LPTR, integer, dimension(*) LEND, integer LNEW)
Definition at line 3041 of file stripack.f.
References insert(), and lstptr().
Referenced by addnod().
subroutine intrsc (real(kind=8), dimension(3) P1, real(kind=8), dimension(3) P2, real(kind=8), dimension(3) CN, real(kind=8), dimension(3) P, integer IER)
Definition at line 3130 of file stripack.f.
Referenced by inside().
integer function jrand (integer N, integer IX, integer IY, integer IZ)
Definition at line 3235 of file stripack.f.
Referenced by trfind().
logical function left (real(kind=8) X1, real(kind=8) Y1, real(kind=8) Z1, real(kind=8) X2, real(kind=8) Y2, real(kind=8) Z2, real(kind=8) X0, real(kind=8) Y0, real(kind=8) Z0)
Definition at line 3299 of file stripack.f.
Referenced by delnod(), edge(), and trmesh().
integer function lstptr (integer LPL, integer NB, integer, dimension(*) LIST, integer, dimension(*) LPTR)
Definition at line 3342 of file stripack.f.
Referenced by addnod(), crlist(), delarc(), delnod(), getsig(), intadd(), intrc1(), nearnd(), sgprnt(), swap(), and trfind().
integer function nbcnt (integer LPL, integer, dimension(*) LPTR)
Definition at line 3399 of file stripack.f.
Referenced by delnod().
integer function nearnd (real(kind=8), dimension(3) P, integer IST, integer N, real(kind=8), dimension(n) X, real(kind=8), dimension(n) Y, real(kind=8), dimension(n) Z, integer, dimension(*) LIST, integer, dimension(*) LPTR, integer, dimension(n) LEND, real(kind=8) AL)
Definition at line 3453 of file stripack.f.
References lstptr(), and trfind().
subroutine optim (real(kind=8), dimension(*) X, real(kind=8), dimension(*) Y, real(kind=8), dimension(*) Z, integer NA, integer, dimension(*) LIST, integer, dimension(*) LPTR, integer, dimension(*) LEND, integer NIT, integer, dimension(2,na) IWK, integer IER)
Definition at line 3693 of file stripack.f.
References swap(), and swptst().
Referenced by delnod(), and edge().
subroutine scoord (real(kind=8) PX, real(kind=8) PY, real(kind=8) PZ, real(kind=8) PLAT, real(kind=8) PLON, real(kind=8) PNRM)
Definition at line 3889 of file stripack.f.
real(kind=8) function store (real(kind=8) X)
Definition at line 3943 of file stripack.f.
Referenced by getsig(), sig0(), sig1(), sig2(), and trfind().
subroutine swap (integer IN1, integer IN2, integer IO1, integer IO2, integer, dimension(*) LIST, integer, dimension(*) LPTR, integer, dimension(*) LEND, integer LP21)
Definition at line 3984 of file stripack.f.
References lstptr().
Referenced by addnod(), delnod(), edge(), and optim().
logical function swptst (integer N1, integer N2, integer N3, integer N4, real(kind=8), dimension(*) X, real(kind=8), dimension(*) Y, real(kind=8), dimension(*) Z)
Definition at line 4095 of file stripack.f.
Referenced by addnod(), crlist(), and optim().
subroutine trans (integer N, real(kind=8), dimension(n) RLAT, real(kind=8), dimension(n) RLON, real(kind=8), dimension(n) X, real(kind=8), dimension(n) Y, real(kind=8), dimension(n) Z)
Definition at line 4176 of file stripack.f.
subroutine trfind (integer NST, real(kind=8), dimension(3) P, integer N, real(kind=8), dimension(n) X, real(kind=8), dimension(n) Y, real(kind=8), dimension(n) Z, integer, dimension(*) LIST, integer, dimension(*) LPTR, integer, dimension(n) LEND, real(kind=8) B1, real(kind=8) B2, real(kind=8) B3, integer I1, integer I2, integer I3)
Definition at line 4244 of file stripack.f.
References jrand(), lstptr(), and store().
Referenced by addnod(), intrc0(), intrc1(), and nearnd().
subroutine trlist (integer N, integer, dimension(*) LIST, integer, dimension(*) LPTR, integer, dimension(n) LEND, integer NROW, integer NT, integer, dimension(nrow,*) LTRI, integer IER)
Definition at line 4681 of file stripack.f.
subroutine trlprt (integer N, real(kind=8), dimension(n) X, real(kind=8), dimension(n) Y, real(kind=8), dimension(n) Z, integer IFLAG, integer NROW, integer NT, integer, dimension(nrow,nt) LTRI, integer LOUT)
Definition at line 4935 of file stripack.f.
subroutine trmesh (integer N, real(kind=8), dimension(n) X, real(kind=8), dimension(n) Y, real(kind=8), dimension(n) Z, integer, dimension(*) LIST, integer, dimension(*) LPTR, integer, dimension(n) LEND, integer LNEW, integer, dimension(n) NEAR, integer, dimension(n) NEXT, real(kind=8), dimension(n) DIST, integer IER)
Definition at line 5128 of file stripack.f.
References addnod(), and left().
Referenced by stripackinterfacemodule::delaunaytriangulation().
subroutine trplot (integer LUN, real(kind=8) PLTSIZ, real(kind=8) ELAT, real(kind=8) ELON, real(kind=8) A, integer N, real(kind=8), dimension(n) X, real(kind=8), dimension(n) Y, real(kind=8), dimension(n) Z, integer, dimension(*) LIST, integer, dimension(*) LPTR, integer, dimension(n) LEND, character*(*) TITLE, logical NUMBR, integer IER)
Definition at line 5549 of file stripack.f.
subroutine trprnt (integer N, real(kind=8), dimension(n) X, real(kind=8), dimension(n) Y, real(kind=8), dimension(n) Z, integer IFLAG, integer, dimension(*) LIST, integer, dimension(*) LPTR, integer, dimension(n) LEND, integer LOUT)
Definition at line 5980 of file stripack.f.
subroutine vrplot (integer LUN, real(kind=8) PLTSIZ, real(kind=8) ELAT, real(kind=8) ELON, real(kind=8) A, integer N, real(kind=8), dimension(n) X, real(kind=8), dimension(n) Y, real(kind=8), dimension(n) Z, integer NT, integer, dimension(*) LISTC, integer, dimension(*) LPTR, integer, dimension(n) LEND, real(kind=8), dimension(nt) XC, real(kind=8), dimension(nt) YC, real(kind=8), dimension(nt) ZC, character*(*) TITLE, logical NUMBR, integer IER)
Definition at line 6240 of file stripack.f.