SWEDivergenceEqnTerms.f90 File Reference
Functions/Subroutines
program swedivergenceequationterms
subroutine readnamelistinputfile (rank)
subroutine initlogger (aLog, rank)
real(kreal) function legendrep10_3 (z)
real(kreal) function legendrep54 (z)
real(kreal) function legendrep52 (z)
subroutine testlinearfunction (aMesh)
subroutine testsphericalharmonic52 (amesh)
subroutine testsphericalharmonic54 (amesh)
subroutine testsphericalharmonic10_3 (amesh, rescale)
subroutine ssrfpackapproximations (aMesh)
subroutine trivariatequadraticapproximations (aMesh)
real(kreal) function quadraticscalarappx (coeffs, xyz)
real(kreal) function, dimension(3) quadraticgradappx (coeffs, xyz)
real(kreal) function quadraticlaplacianappx (coeffs, xyz)
subroutine calculateerror (amesh, gradLinf, gradL2, lapLinf, lapL2, scalarLinf, scalarL2)
Function/Subroutine Documentation
subroutine swedivergenceequationterms::calculateerror (type(spheremesh), intent(inout) amesh, real(kreal), intent(out) gradLinf, real(kreal), intent(out) gradL2, real(kreal), intent(out) lapLinf, real(kreal), intent(out) lapL2, real(kreal), intent(out) scalarLinf, real(kreal), intent(out) scalarL2)
Definition at line 903 of file SWEDivergenceEqnTerms.f90.
Referenced by swedivergenceequationterms().
subroutine swedivergenceequationterms::initlogger (type(logger), intent(out) aLog, integer(kint), intent(in) rank)
Definition at line 387 of file SWEDivergenceEqnTerms.f90.
real(kreal) function swedivergenceequationterms::legendrep10_3 (real(kreal), intent(in) z)
Definition at line 398 of file SWEDivergenceEqnTerms.f90.
Referenced by testsphericalharmonic10_3().
real(kreal) function swedivergenceequationterms::legendrep52 (real(kreal), intent(in) z)
Definition at line 411 of file SWEDivergenceEqnTerms.f90.
Referenced by testsphericalharmonic52().
real(kreal) function swedivergenceequationterms::legendrep54 (real(kreal), intent(in) z)
Definition at line 404 of file SWEDivergenceEqnTerms.f90.
Referenced by testsphericalharmonic54().
real(kreal) function, dimension(3) swedivergenceequationterms::quadraticgradappx (real(kreal), dimension(10), intent(in) coeffs, real(kreal), dimension(3), intent(in) xyz)
Definition at line 855 of file SWEDivergenceEqnTerms.f90.
Referenced by trivariatequadraticapproximations().
real(kreal) function swedivergenceequationterms::quadraticlaplacianappx (real(kreal), dimension(10), intent(in) coeffs, real(kreal), dimension(3), intent(in) xyz)
Definition at line 870 of file SWEDivergenceEqnTerms.f90.
Referenced by trivariatequadraticapproximations().
real(kreal) function swedivergenceequationterms::quadraticscalarappx (real(kreal), dimension(10), intent(in) coeffs, real(kreal), dimension(3), intent(in) xyz)
Definition at line 847 of file SWEDivergenceEqnTerms.f90.
Referenced by trivariatequadraticapproximations().
subroutine swedivergenceequationterms::readnamelistinputfile (integer(kint), intent(in) rank)
Definition at line 363 of file SWEDivergenceEqnTerms.f90.
Referenced by nonlinearsteadyswe(), and swedivergenceequationterms().
subroutine swedivergenceequationterms::ssrfpackapproximations (type(spheremesh), intent(inout) aMesh)
Definition at line 574 of file SWEDivergenceEqnTerms.f90.
References gradl(), ssrfpackinterfacemodule::interpolatescalar(), and ssrfpackinterfacemodule::setsourcerelvort().
Referenced by swedivergenceequationterms().
program swedivergenceequationterms ()
Definition at line 1 of file SWEDivergenceEqnTerms.f90.
References calculateerror(), initlogger(), readnamelistinputfile(), ssrfpackapproximations(), testlinearfunction(), testsphericalharmonic10_3(), trivariatequadraticapproximations(), planeoutputmodule::updatefilename(), vtkoutputmodule::updatetitle(), and vtkoutputmodule::vtkoutput().
subroutine swedivergenceequationterms::testlinearfunction (type(spheremesh), intent(inout) aMesh)
Definition at line 418 of file SWEDivergenceEqnTerms.f90.
Referenced by swedivergenceequationterms().
subroutine swedivergenceequationterms::testsphericalharmonic10_3 (type(spheremesh), intent(inout) amesh, logical(klog), intent(in) rescale)
Definition at line 502 of file SWEDivergenceEqnTerms.f90.
References legendrep10_3().
Referenced by swedivergenceequationterms().
subroutine swedivergenceequationterms::testsphericalharmonic52 (type(spheremesh), intent(inout) amesh)
Definition at line 449 of file SWEDivergenceEqnTerms.f90.
References legendrep52().
subroutine swedivergenceequationterms::testsphericalharmonic54 (type(spheremesh), intent(inout) amesh)
Definition at line 476 of file SWEDivergenceEqnTerms.f90.
References legendrep54().
subroutine swedivergenceequationterms::trivariatequadraticapproximations (type(spheremesh), intent(inout) aMesh)
Definition at line 635 of file SWEDivergenceEqnTerms.f90.
References planemeshmodule::ccwedgesandparticlesaroundpanel(), planemeshmodule::findadjacentpanels(), quadraticgradappx(), quadraticlaplacianappx(), and quadraticscalarappx().
Referenced by swedivergenceequationterms().