SWETestCase2.f90 File Reference
Functions/Subroutines
program nonlinearsteadyswe
subroutine readnamelistinputfile (rank)
subroutine initlogger (aLog, rank)
Function/Subroutine Documentation
subroutine nonlinearsteadyswe::initlogger (type(logger), intent(out) aLog, integer(kint), intent(in) rank)
Definition at line 239 of file SWETestCase2.f90.
program nonlinearsteadyswe ()
Definition at line 1 of file SWETestCase2.f90.
References initlogger(), swesetupmodule::initnonlinearsteadystatetc2(), readnamelistinputfile(), tracersetupmodule::setflowmaplatitudetraceronmesh(), swesetupmodule::setnonlinearsteadystatetc2onmesh(), swedirectsummodule::swerk4timestep(), planeoutputmodule::updatefilename(), and vtkoutputmodule::vtkoutput().
subroutine nonlinearsteadyswe::readnamelistinputfile (integer(kint), intent(in) rank)
Definition at line 200 of file SWETestCase2.f90.