TestCase1.f90 File Reference
Functions/Subroutines
program testcase1
subroutine readnamelistfile (rank)
subroutine initlogger (alog, rank)
Function/Subroutine Documentation
subroutine testcase1::initlogger (type(logger), intent(out) alog, integer(kint), intent(in) rank)
Definition at line 255 of file TestCase1.f90.
subroutine testcase1::readnamelistfile (integer(kint), intent(in) rank)
Definition at line 229 of file TestCase1.f90.
program testcase1 ()
Definition at line 1 of file TestCase1.f90.
References advectionmodule::advectionrk4timestep(), tracersetupmodule::initcosinebelltracer(), initlogger(), readnamelistfile(), tracersetupmodule::setcosinebelltraceronmesh(), advectionmodule::testcase1velocity(), planeoutputmodule::updatefilename(), and vtkoutputmodule::vtkoutput().