TwoDipoles.f90 File Reference
Functions/Subroutines
program twodipolesmain
subroutine readnamelistfile (rank)
subroutine converttorelativetolerances (aMesh, maxCircTol, vortVarTol, lagVarTol)
subroutine storelagrangianxcoordinateintracer (aMesh, tracerID)
subroutine initlogger (aLog, rank)
Function/Subroutine Documentation
subroutine twodipolesmain::converttorelativetolerances (type(planemesh), intent(in) aMesh, real(kreal), intent(inout) maxCircTol, real(kreal), intent(inout) vortVarTol, real(kreal), intent(inout) lagVarTol)
Definition at line 366 of file TwoDipoles.f90.
References planemeshmodule::maximumcirculation(), planemeshmodule::maximumlagrangianparametervariation(), and planemeshmodule::maximumvorticityvariation().
subroutine twodipolesmain::initlogger (type(logger), intent(inout) aLog, integer(kint), intent(in) rank)
Definition at line 396 of file TwoDipoles.f90.
subroutine twodipolesmain::readnamelistfile (integer(kint), intent(in) rank)
Definition at line 289 of file TwoDipoles.f90.
subroutine twodipolesmain::storelagrangianxcoordinateintracer (type(planemesh), intent(inout) aMesh, integer(kint), intent(in) tracerID)
Definition at line 376 of file TwoDipoles.f90.
program twodipolesmain ()
Definition at line 1 of file TwoDipoles.f90.
References converttorelativetolerances(), planemeshmodule::gettotalcirculation(), planemeshmodule::gettotalenstrophy(), planemeshmodule::gettotalke(), planetracermodule::initdipoleidtracer(), planemeshmodule::initializerectangle(), refineremeshmodule::initialrefinement(), initlogger(), planevorticitymodule::inittwodipoles(), planeoutputmodule::outputforvtk(), readnamelistfile(), planedirectsummodule::rk4timestepnorotation(), planetracermodule::setdipoleidtraceronmesh(), planevorticitymodule::settwodipolesonmesh(), storelagrangianxcoordinateintracer(), planemeshmodule::totalarea(), spheremeshmodule::totalenstrophy(), and planeoutputmodule::updatefilename().